// The overworld slice (overworld stream, M2; gameplay spec 5, the compact
// scope of docs/PLAN.md): three lattice areas of 3 x 3 screens of 16 x 16
// tiles, edge to edge, and the secret cave under Cliff Hollow.
//
//        col 3 (x 6-8)          col 4 (x 9-11)
//   row 2   ow-3-2 Barrowfield  v1 Mossbrook (village; the game starts in its Square)
//   row 3                       ow-4-3 Crownhold (the castle; the king who sent for you)
//
// The road: Crownhold Courtyard (1,1) -> Castle Road (1,0) -> Mossbrook Lane
// (1,2) -> the Square (1,1) -> West Gate (0,1) -> Barrow Road (2,1) ->
// Barrow Crossing (1,1) -> The Old Barrow (1,2), whose door leads into D1
// (dungeons/d1.js pins both spots, CONTRACTS 8.10). Screen edges open on
// columns / rows 6-9 where two screens join. Generated from one layout
// sheet, so shared edges line up; edit both sides of an edge together.
//
// Markers: G = a spawn group of the area's roster (entities/spawn-group.js).
// People stand by spawnsAt (entities/npcs/slice.js). Tiles: world/tiles/
// overworld.js and town.js (H house, h its door, M castle wall, m gate).
import { registerArea, START } from '../areas.js';
import { registerPlace } from '../../game/places.js';
import { registerPrologue } from '../../game/progress.js';

// The D1 door and the spot outside it (CONTRACTS 8.10: both pinned).
export const D1_ENTRANCE = { area: 'd1', screen: [3, 9], x: 8, z: 10.4, yaw: Math.PI };
export const D1_EXIT = { area: 'ow-3-2', screen: [1, 2], x: 8, z: 9, yaw: 0 };
// Where the king waits: just past the courtyard gate (registerPlace 'castle' below).
// A new game starts at areas.js's START (Mossbrook) instead; there is no second copy of it here.
const CROWNHOLD_GATE = { area: 'ow-4-3', screen: [1, 1], x: 8, z: 9, yaw: Math.PI };

const field = (of, count = [1, 2], extra = {}) => ({ type: 'group', of, count, ...extra });

registerArea({
  id: 'ow-4-3',
  name: 'Crownhold',
  kind: 'overworld',
  tileset: 'town',
  lighting: 'day',
  music: 'overworld',
  screen: [16, 16],
  origin: [9, 6],
  start: [1, 1],
  spawns: { G: field(['hopper', 'blob', 'blob']) },
  screens: {
    '0,0': {
      name: "West Pasture",
      // A pair of pots by the fence line (fun audit item 2: every combat screen earns a find).
      // A way west into Drover's Cut, the other end of the loop back to Barrowfield (fun audit
      // item 1); rows 6-8 line up with Drover's Cut's own east gap.
      rows: [
        'TTTTTTTTTTTTTTTT',
        'TTTT......,,,..T',
        'TT....G.....B..T',
        'TT..,,,........T',
        'T...,,,...RR...T',
        'T.........R....T',
        '...B............',
        '.........G......',
        '.......,,.......',
        'T.R....,,....B..',
        'T..v..........vT',
        'T...B.......,,.T',
        'T.........G....T',
        'TT.............T',
        'TTT............T',
        'TTTTTT....TTTTTT',
      ],
    },
    '1,0': {
      name: "Castle Road",
      // The public road leads an unarmed hero to the king. Pasture encounters
      // stay off this route; wildflowers and pots still reward the first trip.
      spawnsAt: {
        '12,10': { type: 'npc', name: 'Cobb', palette: { tunic: 0x5a7a4a, tunicLight: 0x7a9a6a, cap: 0x8a6a3a }, wander: 2, lines: ['Flour for the castle kitchens. Long walk on a hot day.'] },
      },
      rows: [
        'TTTTTT::::TTTTTT',
        'TTT...::::...TTT',
        'TT,,,.::::.,..TT',
        'T....f::::...v.T',
        'T.B..f::::..R..T',
        'Tv...f::::.....T',
        '.,..::::::::::::',
        '::::::::::::::::',
        '......::::......',
        '..R..i::::..B...',
        'T.....::::.....T',
        'TT..,.::::.,..TT',
        'TTT...::::...TTT',
        'T.....::::.....T',
        'T.....::::.....T',
        'TTTTTT::::TTTTTT',
      ],
    },
    '2,0': {
      name: "East Pasture",
      // A cracked rock among the plain ones (fun audit item 2): a bomb opens it onto Pasture Hollow.
      warps: { y: { area: 'cave-crownhold-1', screen: [0, 0], x: 6, z: 7.4, yaw: Math.PI } },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T..,,,......TTTT',
        'T..B.....G....TT',
        'T.............TT',
        'T...RR...,,,...T',
        'T...R.k..,,,...T',
        '...........B...T',
        '......G........T',
        '...............T',
        '..B....~~~.....T',
        'T.....~~~~~..R.T',
        'T......~~~.....T',
        'T..,,......G...T',
        'T.............TT',
        'T............TTT',
        'TTTTTT....TTTTTT',
      ],
    },
    '0,1': {
      name: "Old Orchard",
      // Pots between the trees (fun audit item 2).
      rows: [
        'TTTTTT....TTTTTT',
        'T.T..T..T..T...T',
        'T..v.......v...T',
        'T.T..T..T..T...T',
        'T......G.......T',
        'T.T..T..T..T...T',
        'T..............T',
        'T.T..T..T..T..BT',
        'T..........G...T',
        'T.T..T..T..T...T',
        'T..............T',
        'T.T..T..T..T...T',
        'T..............T',
        'T.T..T..T..T...T',
        'T..............T',
        'TTTTTT....TTTTTT',
      ],
    },
    '1,1': {
      name: "Crownhold Courtyard",
      // A safe royal audience and gathering place for independently travelling
      // friends. The king watches the approach from the four-hour mosaic.
      spawnsAt: {
        '7,5': { type: 'npc-king', wander: 0 },
        '5,7': { type: 'npc', name: 'Guard Oswin', palette: { tunic: 0x6a6f7c, tunicLight: 0x8a8f9c, cap: 0x3a3a44, extras: ['helm'] }, wander: 2, schedule: 'always', lines: ['The king has been waiting for you.', 'Straight ahead. He is expecting you.'] },
        '10,7': { type: 'npc', name: 'Guard Pell', palette: { tunic: 0x6a6f7c, tunicLight: 0x8a8f9c, cap: 0x3a3a44, extras: ['helm'] }, wander: 2, schedule: 'always', lines: ['West of the village the old barrow has woken.', 'Things crawl out of it at night. Mind yourself.'] },
      },
      rows: [
        'TTTTTT....TTTTTT',
        'TMMMMMMmmMMMMMMT',
        'TM,,,..::..,,,MT',
        'TM.MMMM..MMMM.MT',
        'TM.MMMM..MMMM.MT',
        'TM...::o::....MT',
        'TM...:o:o:....MT',
        'TM..f..aa..f..MT',
        'TM.v...aa...v.MT',
        'TM..,,.aa.,,..MT',
        'TM.....aa.....MT',
        'TM..B..aa..B..MT',
        'TM,,,..aa..,,,MT',
        'TMMMMMMMMMMMMMMT',
        'T,.............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
    '2,1': {
      name: "Stone Circle",
      chests: { '2,12': { grant: 'coins', amount: 50 } },
      rows: [
        'TTTTTT....TTTTTT',
        'T..............T',
        'T...R.....R....T',
        'T..............T',
        'T.R....,,....R.T',
        'T.....,gg,.....T',
        'T.....,gg,.....T',
        'T.R....,,....R.T',
        'T.......G......T',
        'T...R.....R....T',
        'T..............T',
        'T.B..........B.T',
        'TBCB.......G...T',
        'T.B............T',
        'T..............T',
        'TTTTTT....TTTTTT',
      ],
    },
    '0,2': {
      name: "South Fields",
      // One bush here is like any other until it is cut (fun audit item 2): hidden stairs down to
      // Sunken Nook.
      warps: { j: { area: 'cave-crownhold-2', screen: [0, 0], x: 6, z: 7.4, yaw: Math.PI } },
      rows: [
        'TTTTTT....TTTTTT',
        'T..............T',
        'T.,,,......B...T',
        'T.,,,...G......T',
        'T..............T',
        'T.....RR.......T',
        'T......R........',
        'T.K.............',
        'T.........G.....',
        'T...............',
        'T...,,,........T',
        'T...,,,....R...T',
        'T..............T',
        'T..............T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
    '1,2': {
      name: "Moat Meadow",
      // Pots past the reeds (fun audit item 2).
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T.~~~~~~~~~~~~.T',
        'T.~~~~~~~~~~~~.T',
        'T..............T',
        'T....G.........T',
        'T..............T',
        '................',
        '..B.....,,....B.',
        '........,,......',
        '..........G.....',
        'T..............T',
        'T...R.......R..T',
        'T..v.......v...T',
        'T..............T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
    '2,2': {
      name: "Thicket Edge",
      // Pots in the thicket (fun audit item 2).
      rows: [
        'TTTTTT....TTTTTT',
        'T..............T',
        'T...TT....G....T',
        'T...TT.........T',
        'T..v.......v...T',
        'T.........B....T',
        '...............T',
        '.....G.........T',
        '...............T',
        '..R.......,,,..T',
        'T.........,,,..T',
        'T..............T',
        'T...B....TTTT..T',
        'T........TTTT..T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
  },
});

registerArea({
  id: 'v1',
  name: 'Mossbrook',
  kind: 'town',
  groundPalette: { grass:[0x79ae89,0x568b77,0xa5c99a], path:[0xc1ac8c,0x9c8c7e,0xdac7a4] },
  housePalette: { roof:0x945877, roofDark:0x633f60, plaster:0xe8d1aa, timber:0x64516a },
  tileset: 'town',
  lighting: 'day',
  music: 'village',
  screen: [16, 16],
  origin: [9, 3],
  start: [1, 2],
  screens: {
    '0,0': {
      name: "Orchard Row",
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T.T.T.T.T.T....T',
        'T.........,,...T',
        'T.T.T.T.T.T....T',
        'T........HHH...T',
        'T.T.T.T..HhH...T',
        'T........pp.....',
        'T........pppppp.',
        'T.,,,....pp.....',
        'T.,,,....pp.....',
        'T........pp....T',
        'T.f.f.f..pp....T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '1,0': {
      name: "Chapel Green",
      spawnsAt: {
        '10,5': { type: 'npc', name: 'Sister Anwe', palette: { tunic: 0xd8d0c0, tunicLight: 0xf0e8d8, cap: 0xd8d0c0, extras: [['hood', 0xe8e0d0]] }, lines: ['The graves here are quiet. The barrow is not.'] },
      },
      rows: [
        'TTT.......TTTTTT',
        'T....HHHHHH....T',
        'T....HHHHHH....T',
        'T....HHHhHH....T',
        'T.......pp.....T',
        'T.g.g...pp..,,.T',
        '........pp..,,..',
        '..g.g..pppp.....',
        'pppppppppppppppp',
        'pppppppppppppppp',
        'T.....pppp.....T',
        'T.,,..pppp..v.vT',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '2,0': {
      name: "Hill Farm",
      spawnsAt: {
        '11,6': { type: 'npc', name: 'Farmer Dobb', palette: { tunic: 0x8a6a3a, tunicLight: 0xaa8a5a, cap: 0xc8b070 }, lines: ['The pots by my door? Break them if you like. My wife will not.'] },
      },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T.ffffffff.....T',
        'T.f,,,,,,f..HHHT',
        'T.f,,,,,,f..HhHT',
        'T.f......f.....T',
        'T.ffff.fff.....T',
        '...............T',
        'ppppppp........T',
        'pppppppppp.....T',
        '.........p.....T',
        'T.B......p..v..T',
        'T........p.....T',
        'T........p.....T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '0,1': {
      name: "West Gate",
      // Rook's stolen dice wait in the den beneath the northwest stair-bush.
      warps: { j: { area: 'rook-den', screen: [0,2], x: 7.5, z: 9.5, yaw: Math.PI } },
      spawnsAt: {
        '12,8': { type: 'npc', name: 'Rook', palette: { tunic: 0x7a5a8a, tunicLight: 0x9a7aaa }, lines: ['West is Barrowfield. Take the road and keep south.'] },
      },
      rows: [
        'TTTTTTppppTTTTTT',
        'T.TT..pppp..HHHT',
        'T.T...pppp..HhHT',
        'TBBK..pppp.....T',
        'T.f.f.pppp.....T',
        'TBB...pppp..,,.T',
        'pppppppppppppppp',
        'pppppppppppppppp',
        '......pppp......',
        '..,,..pppp..v...',
        'T.....pppp.....T',
        'T.HHH.pppp.,,,.T',
        'T.HhH.pppp.....T',
        'T.....pppp..T..T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '1,1': {
      name: "Mossbrook Square",
      warps: { y: { area: 'cellar-tobin', screen: [0, 0], x: 5.5, z: 8, yaw: 0 }, '12,10': { area: 'mossbrook-fair', screen: [0,0], x: 8.5, z: 14, yaw: Math.PI } },
      spawnsAt: {
        '9,12': { type: 'npc-mira' },
        '5,4': { type: 'npc-shop', shop: 'v1-shop' },
        '10,4': { type: 'npc-smith' },
        '13,5': { type: 'npc-inventor' }, // the Sprint Boots (gameplay spec: the inventor in V1, before D1)
        '5,11': { type: 'npc-inn', inn: 'inn-1' },
        '10,11': { type: 'npc', name: 'Hettie', palette: { extras: ['straw-hat'] }, lines: ['Welcome to Mossbrook!', 'The inn lets you rest and wakes you there if you fall.'] },
        '2,8': { type: 'npc', name: 'Pip', personality: 'cheery', palette: { tunic: 0x4a9a5a, tunicLight: 0x6aba7a, hair: 0xd8a040, cap: 0xd05a3a, kid: true, extras: ['scarf'] }, lines: ['I am Pip! I can run faster than a slime. Probably.'] },
        '13,7': { type: 'npc', name: 'Old Tobin', personality: 'grumpy', palette: { tunic: 0x5a5a6a, tunicLight: 0x7a7a8a, hair: 0xc8c8c8, cap: 0x3a3a44, extras: ['beard', ['hood', 0x6a4a34]] }, lines: ['Another adventurer. Wonderful.', 'Stay off my bench.'] },
        '5,14': { type: 'npc', name: 'Nell', personality: 'gossip', palette: { tunic: 0xa04a7a, tunicLight: 0xc06a9a, hair: 0x3a2418, cap: 0xe8d8b0, extras: ['bun', ['scarf', 0x3a8a9a]] }, lines: ['Oh! You must be the one the king sent for!', 'Everyone is talking about you. Well, I am.'] },
        '12,14': { type: 'npc', name: 'Rowan', personality: 'worker', palette: { tunic: 0x7a5a3a, tunicLight: 0x9a7a5a, hair: 0x8a3a20, cap: 0x5a7a3a, extras: ['straw-hat'] }, lines: ['Mind the fence posts, I just set them.'] },
        '2,4': { type: 'npc', name: 'Tam', palette: { tunic: 0x4a7a4a, tunicLight: 0x6a9a6a }, lines: ['Cut the bushes! Sometimes there are coins under them.'] },
      },
      rows: [
        'TTTTTTppppTTTTTT',
        'THHHHH.pp.HHHHHT',
        'THHHHH.pp.HHHHHT',
        'THHhHH.pp.HHhHHT',
        'T..pp..pp..pp..T',
        'T&.pppppppppp.&T',
        'ppppppp~~ppppppp',
        'pppppp~~~~pppp%p',
        'pppppp~~~~pppppp',
        'ppppppp~~ppppppp',
        'T..pppppppppV..T',
        'T..pp..pp..pp..T',
        'THHhH..pp..HhHHT',
        'THHHH..pp..HHHHT',
        'T......pp.@....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '2,1': {
      name: "Mill Pond",
      rows: [
        'TTTTTTppppTTTTTT',
        'T......pp......T',
        'T..~~~~........T',
        'T.~~~~~~~...HHHT',
        'T.~~~~~~~...HhHT',
        'T..~~~~~.......T',
        'ppppppp.........',
        'pppppppppppppppp',
        '...........ppppp',
        '..,,,......p....',
        'T.,,,..v...p...T',
        'T..........p...T',
        'T.T........p...T',
        'T..........pp..T',
        'T.....ppppppp..T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '0,2': {
      name: "Well Corner",
      rows: [
        'TTTTTTppppTTTTTT',
        'T.....pppp.....T',
        'T.HHH.pppp.....T',
        'T.HhH.pppp..,,.T',
        'T.....pppp.....T',
        'T.,,..pppp.....T',
        'T.....pppppppppp',
        'T.....pppppppppp',
        'T.R.............',
        'T......B........',
        'T.T............T',
        'T......,,,.....T',
        'T.B............T',
        'T..............T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
    '1,2': {
      name: "Mossbrook Lane",
      spawnsAt: {
        '12,4': { type: 'npc', name: 'Old Wick', lines: ['They say the barrow west of here keeps a throwing blade', 'that comes back to your hand.'] },
      },
      rows: [
        'TTTTTT;;;;TTTTTT',
        'THHHH.;;;;.HHHHT',
        'THHhH.;;;;.HhHHT',
        'T.....;;;;.....T',
        'T.v...;;;;...v.T',
        'T.....;;;;.....T',
        ';;;;;;;;;;;;;;;;',
        ';;;;;;;;;;;;;;;;',
        '......;;;;......',
        '.HHH..;;;;..HHH.',
        'THhH..;;;;..HhHT',
        'T.,...;;;;...,.T',
        'T.f...;;;;...f.T',
        'T.f..i;;;;...f.T',
        'T.....;;;;.....T',
        'TTTTTT;;;;TTTTTT',
      ],
    },
    '2,2': {
      name: "Lane End",
      rows: [
        'TTTTTTppppTTTTTT',
        'T.....pppp.....T',
        'T.,,..pppp..HHHT',
        'T.....pppp..HhHT',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'pppppppppp.....T',
        'pppppppppp.....T',
        '...............T',
        '..f.f.f........T',
        'T...........B..T',
        'T.,,,..........T',
        'T........TT....T',
        'T....v.........T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
  },
});

registerArea({
  id: 'ow-3-2',
  name: 'Barrowfield',
  kind: 'overworld',
  tileset: 'town',
  lighting: 'day',
  music: 'overworld',
  screen: [16, 16],
  origin: [6, 3],
  start: [2, 1],
  spawns: { G: field(['hopper', 'blob', 'buzzer']) },
  screens: {
    '0,0': {
      name: "Cliff Hollow",
      warps: { D: { area: 'cave-barrow', screen: [0, 0], x: 6, z: 7.4, yaw: Math.PI } },
      spawns: { G: field(['leaper', 'hopper'], [1, 2], { rare: ['treasure-slime'] }) },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T.2222222222...T',
        'T.2222222222...T',
        'T.##########...T',
        'T.####D#####...T',
        'T......p.......T',
        'T..R...p...G....',
        'T......pp.......',
        'T.G.....pppppppp',
        'T........ppppppp',
        'T.B............T',
        'T.....pppp..R..T',
        'T.....pppp.....T',
        'T.T...pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '1,0': {
      name: "Buzzing Heath",
      spawns: { G: field(['buzzer', 'buzzer', 'hopper'], [1, 2]) },
      // Pots in the heather (fun audit item 2).
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T.T..........T.T',
        'T...G..........T',
        'T......,,,.....T',
        'T.R....,,,...G.T',
        'T..v.......v...T',
        '................',
        'pppppppppppppppp',
        'pppppppppppppppp',
        '......pppp......',
        'T.B...pppp..B..T',
        'T.....pppp.....T',
        'T.G...pppp.....T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '2,0': {
      name: "Stump Wood",
      spawns: { G: field(['stump', 'stump', 'blob'], [1, 2]) },
      // A cracked rock among the stumps (fun audit item 2): a bomb opens it onto Stump Hollow.
      warps: { y: { area: 'cave-barrowfield-1', screen: [0, 0], x: 6, z: 7.4, yaw: Math.PI } },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T.T.T.T.T.T.T..T',
        'T..............T',
        'T.T...G...T.T..T',
        'T........kT....T',
        'T.T.T.T........T',
        '...............T',
        'ppppppp....G...T',
        'pppppppp.......T',
        '......ppp..T.T.T',
        'T.T....ppp.....T',
        'T.......ppp....T',
        'T.G......pp....T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '0,1': {
      name: "Leaper Hollow",
      spawns: { G: field(['leaper', 'blob-blue'], [1, 2]) },
      // Pots by the crossing (fun audit item 2).
      rows: [
        'TTTTTTppppTTTTTT',
        'T.TT..pppp.....T',
        'T.T...pppp..R..T',
        'Tv....pppp...v.T',
        'T.R.....G......T',
        'T............G.T',
        'T........ppppppp',
        'T......ppppppppp',
        'T.G....pp.......',
        'T......pp.......',
        'T.TT...pp...R..T',
        'T......pp......T',
        'T..R...pp....T.T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '1,1': {
      name: "Barrow Crossing",
      // One bow teaches the starter shield after the road's close-range pair.
      // Its long draw commits to a direction; later bows retain tier-two arrows.
      chest: 'heart-piece',
      spawnsAt: {
        '4,8': {type:'archer',crowned:false,arrowTier:1,shotTell:.8},
        '11,10': {type:'blob',crowned:false},
      },
      rows: [
        'TTTTTTppppTTTTTT',
        'T.T...pppp...T.T',
        'T.....pppp.....T',
        'T.R...pppp.....T',
        'T.....pppp.....T',
        'T.....pppp...C.T',
        'pppppppppppppppp',
        'pppppppppppppppp',
        '......pppp......',
        '..B...pppp..R...',
        'T.....pppp.....T',
        'T.,,..pppp.....T',
        'T.....pppp.....T',
        'T.T...pppp...T.T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '2,1': {
      name: "Barrow Road",
      // One bush here hides stairs down to Roadside Nook (fun audit item 2).
      warps: { j: { area: 'cave-barrowfield-2', screen: [0, 0], x: 6, z: 7.4, yaw: Math.PI } },
      spawnsAt: {
        '3,5': {type:'blob',crowned:false},
        '11,9': {type:'hopper',crowned:false},
      },
      rows: [
        'TTTTTTppppTTTTTT',
        'T.T...pppp...T.T',
        'T.TT..pppp.....T',
        'T.....pppp..R..T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'pppppppppppppppp',
        'pppppppppppppppp',
        '................',
        '..R.....B.......',
        'T..............T',
        'T..K...........T',
        'T.........TT...T',
        'T....,,...TT...T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '0,2': {
      name: "Archer Ridge",
      spawns: { G: field(['archer', 'hopper'], [1, 2]) },
      // Pots along the back wall (fun audit item 2).
      rows: [
        'TTTTTTppppTTTTTT',
        'T.....pppp.....T',
        'T.#####.pp.....T',
        'T.#####.pp..G..T',
        'T.......pp.....T',
        'T.G.....pp.....T',
        'T.......pppppppp',
        'T.......pppppppp',
        'T.R.............',
        'T.........G.....',
        'T...B..........T',
        'T.........R....T',
        'T.T............T',
        'T......B.......T',
        'T..v.......v...T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
    '1,2': {
      name: "The Old Barrow",
      // A sleeping root and slime guard the final approach. Clear them to drink
      // from the wayside spring before descending into the first dungeon.
      warps: { D: D1_ENTRANCE },
      spawnsAt: {
        '12,10': { type: 'npc', name: 'Warden Cray', palette: { tunic: 0x5a6a4a, tunicLight: 0x7a8a6a }, lines: ['That door opened on its own a week ago.', 'Small keys you find in there open only doors in there.'] },
        '3,10': {type:'stump',crowned:false},
        '12,12': {type:'blob',crowned:false},
      },
      rows: [
        'TTTTTTppppTTTTTT',
        'T.T...pppp...T.T',
        'T.....pppp.....T',
        'T.T.#######....T',
        'T...#22222##...T',
        'T..##222222#.T.T',
        '...#########....',
        '...####DD###....',
        '.....pppp.......',
        '..R.pppppp..R...',
        'T......pp......T',
        'T.T.O..pp....T.T',
        'T..R...pp......T',
        'T......pp......T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
    '2,2': {
      name: "Barrow Meadow",
      spawns: { G: field(['blob', 'buzzer'], [1, 2], { rare: ['treasure-slime'] }) },
      chests: { '8,11': 'heart-piece' },
      // The unused guardian gets a post (fun audit: a set piece on the heart-piece chest).
      spawnsAt: { '8,9': { type: 'guardian', wander: 1 } },
      // A way south into Drover's Cut (fun audit item 1: a loop, not the same 3 screens back to
      // Mossbrook). Cols 1-4 line up with Drover's Cut's own north gap; edit both sides together.
      rows: [
        'TTTTTTppppTTTTTT',
        'T.....pppp.....T',
        'T.,,..pppp.....T',
        'T.....pppp..G..T',
        'T.R...pppp.....T',
        'T.....pppp.....T',
        'pppppppppp.....T',
        'pppppppppp.....T',
        '..........B....T',
        '..G............T',
        'T......BBB.....T',
        'T......BCB.....T',
        'T......BBB..R..T',
        'T..............T',
        'T..............T',
        'T....TTTTTTTTTTT',
      ],
    },
  },
});

// A loop, not the same 3 screens back (fun audit item 1): one screen south of Barrow Meadow and
// west of West Pasture closes Crownhold Castle -> west -> north back into Barrowfield, so the
// road is a circuit instead of a dead-end retrace through Mossbrook every time. Global screen
// (8, 6): south neighbour of Barrow Meadow (ow-3-2 2,2, origin [6, 3]) and west neighbour of West
// Pasture (ow-4-3 0,0, origin [9, 6]) by tile adjacency alone (world/areas.js); no warps needed.
registerArea({
  id: 'ow-pass',
  name: "Drover's Cut",
  kind: 'overworld',
  tileset: 'town',
  lighting: 'day',
  music: 'overworld',
  screen: [16, 16],
  origin: [8, 6],
  start: [0, 0],
  screens: {
    '0,0': {
      name: "Drover's Cut",
      rows: [
        'T....TTTTTTTTTTT',
        'T..............T',
        'T....R.........T',
        'T..............T',
        'T.......T......T',
        'T..............T',
        'T...............',
        'T...............',
        'T...............',
        'T..............T',
        'T....T.........T',
        'T..............T',
        'T..,,..........T',
        'T..............T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
  },
});

// The secret under Cliff Hollow: one small cave room (interior column 300).
registerArea({
  id: 'cave-barrow',
  name: 'Hollow Cave',
  kind: 'cave',
  tileset: 'dungeon',
  lighting: 'crypt',
  camera: 'interior',
  rooms: true,
  screen: [12, 9],
  at: [300 * 16, 0],
  warps: { X: { area: 'ow-3-2', screen: [0, 0], x: 6.5, z: 5.6, yaw: 0 } },
  screens: {
    '0,0': {
      name: 'Hollow Cave',
      chest: 'heart-piece',
      spawnsAt: { '5,3': { type: 'guardian', wander: 1 } },
      rows: [
        'WWWWWWWWWWWW',
        'W..........W',
        'W..S....S..W',
        'W..........W',
        'W....c.....W',
        'W..........W',
        'W..F....F..W',
        'W..........W',
        'WWWWWXXWWWWW',
      ],
    },
  },
});

registerPlace({ id: 'castle', name: 'Crownhold Castle', kind: 'castle', order: 10, spot: CROWNHOLD_GATE });
registerPlace({ id: 'v1', name: 'Mossbrook', kind: 'village', order: 20, spot: { area: 'v1', screen: [1, 2], x: 8, z: 12, yaw: Math.PI } });
registerPlace({ id: 'inn-1', name: 'The Mossy Kettle', kind: 'inn', order: 21, spot: { area: 'v1', screen: [1, 1], x: 5.5, z: 10, yaw: 0 } });
registerPlace({ id: 'cave-barrow', name: 'Hollow Cave', kind: 'cave', order: 60, spot: { area: 'ow-3-2', screen: [0, 0], x: 6.5, z: 5.6, yaw: 0 }, area: 'cave-barrow' });
registerPrologue({ spot: START });
