// The overworld slice (overworld stream, M2; gameplay spec 5, the compact
// scope of docs/PLAN.md): three lattice areas of 3 x 3 screens of 16 x 16
// tiles, edge to edge, and the secret cave under Cliff Hollow.
//
//        col 3 (x 6-8)          col 4 (x 9-11)
//   row 2   ow-3-2 Barrowfield  v1 Mossbrook (village)
//   row 3                       ow-4-3 Crownhold (the castle; the game starts here)
//
// The road: Crownhold Courtyard (1,1) -> Castle Road (1,0) -> Mossbrook Lane
// (1,2) -> the Square (1,1) -> West Gate (0,1) -> Barrow Road (2,1) ->
// Barrow Crossing (1,1) -> The Old Barrow (1,2), whose door leads into D1
// (dungeons/d1.js pins both spots, CONTRACTS 8.10). Screen edges open on
// columns / rows 6-9 where two screens join. Generated from one layout
// sheet, so shared edges line up; edit both sides of an edge together.
//
// Markers: G = a spawn group of the area's roster (entities/spawn-group.js).
// People stand by spawnsAt (entities/npcs/slice.js). Tiles: world/tiles/
// overworld.js and town.js (H house, h its door, M castle wall, m gate).
import { registerArea } from '../areas.js';
import { registerPlace } from '../../game/places.js';
import { registerPrologue } from '../../game/progress.js';

// The D1 door and the spot outside it (CONTRACTS 8.10: both pinned).
export const D1_ENTRANCE = { area: 'd1', screen: [3, 9], x: 8, z: 10.4, yaw: Math.PI };
export const D1_EXIT = { area: 'ow-3-2', screen: [1, 2], x: 8, z: 9, yaw: 0 };
// Where a new game starts: the castle courtyard, facing the king.
export const CASTLE_START = { area: 'ow-4-3', screen: [1, 1], x: 8, z: 9, yaw: Math.PI };

const field = (of, count = [1, 2], extra = {}) => ({ type: 'group', of, count, ...extra });

registerArea({
  id: 'ow-4-3',
  name: 'Crownhold',
  kind: 'overworld',
  tileset: 'town',
  lighting: 'day',
  music: 'overworld',
  screen: [16, 16],
  origin: [9, 6],
  start: [1, 1],
  spawns: { G: field(['hopper', 'blob', 'blob']) },
  screens: {
    '0,0': {
      name: "West Pasture",
      rows: [
        'TTTTTTTTTTTTTTTT',
        'TTTT......,,,..T',
        'TT....G.....B..T',
        'TT..,,,........T',
        'T...,,,...RR...T',
        'T.........R....T',
        'T..B............',
        'T........G......',
        'T......,,.......',
        'T.R....,,....B..',
        'T..............T',
        'T...B.......,,.T',
        'T.........G....T',
        'TT.............T',
        'TTT............T',
        'TTTTTT....TTTTTT',
      ],
    },
    '1,0': {
      name: "Castle Road",
      spawns: {},
      rows: [
        'TTTTTTppppTTTTTT',
        'TTT...pppp...TTT',
        'TT..,.pppp.,..TT',
        'T....fpppp.....T',
        'T.B..fpppp..R..T',
        'T....fpppp.....T',
        'pppppppppppppppp',
        'pppppppppppppppp',
        '......pppp......',
        '..R..ipppp..B...',
        'T.....pppp.....T',
        'TT..,.pppp.,..TT',
        'TTT...pppp...TTT',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '2,0': {
      name: "East Pasture",
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T..,,,......TTTT',
        'T..B.....G....TT',
        'T.............TT',
        'T...RR...,,,...T',
        'T...R....,,,...T',
        '...........B...T',
        '......G........T',
        '...............T',
        '..B....~~~.....T',
        'T.....~~~~~..R.T',
        'T......~~~.....T',
        'T..,,......G...T',
        'T.............TT',
        'T............TTT',
        'TTTTTT....TTTTTT',
      ],
    },
    '0,1': {
      name: "Old Orchard",
      rows: [
        'TTTTTT....TTTTTT',
        'T.T..T..T..T...T',
        'T..............T',
        'T.T..T..T..T...T',
        'T......G.......T',
        'T.T..T..T..T...T',
        'T..............T',
        'T.T..T..T..T..BT',
        'T..........G...T',
        'T.T..T..T..T...T',
        'T..............T',
        'T.T..T..T..T...T',
        'T..............T',
        'T.T..T..T..T...T',
        'T..............T',
        'TTTTTT....TTTTTT',
      ],
    },
    '1,1': {
      name: "Crownhold Courtyard",
      spawns: {},
      spawnsAt: {
        '7,5': { type: 'npc-king' },
        '5,7': { type: 'npc', name: 'Guard Oswin', palette: { tunic: 0x6a6f7c, tunicLight: 0x8a8f9c, cap: 0x3a3a44 }, lines: ['The king has been waiting for you.', 'Mossbrook is north, up the road past the gate.'] },
        '10,7': { type: 'npc', name: 'Guard Pell', palette: { tunic: 0x6a6f7c, tunicLight: 0x8a8f9c, cap: 0x3a3a44 }, lines: ['West of the village the old barrow has woken.', 'Things crawl out of it at night. Mind yourself.'] },
      },
      rows: [
        'TTTTTT....TTTTTT',
        'TMMMMMMmmMMMMMMT',
        'TM,,,..pp..,,,MT',
        'TM.MMMMMMMMMM.MT',
        'TM.MMMMMMMMMM.MT',
        'TM............MT',
        'TM............MT',
        'TM..f..pp..f..MT',
        'TM.....pp.....MT',
        'TM..,,.pp.,,..MT',
        'TM.....pp.....MT',
        'TM..B..pp..B..MT',
        'TM,,,..pp..,,,MT',
        'TMMMMMMMMMMMMMMT',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
    '2,1': {
      name: "Stone Circle",
      chests: { '2,12': { grant: 'coins', amount: 50 } },
      rows: [
        'TTTTTT....TTTTTT',
        'T..............T',
        'T...R.....R....T',
        'T..............T',
        'T.R....,,....R.T',
        'T.....,gg,.....T',
        'T.....,gg,.....T',
        'T.R....,,....R.T',
        'T.......G......T',
        'T...R.....R....T',
        'T..............T',
        'T.B..........B.T',
        'TBCB.......G...T',
        'T.B............T',
        'T..............T',
        'TTTTTT....TTTTTT',
      ],
    },
    '0,2': {
      name: "South Fields",
      rows: [
        'TTTTTT....TTTTTT',
        'T..............T',
        'T.,,,......B...T',
        'T.,,,...G......T',
        'T..............T',
        'T.....RR.......T',
        'T......R........',
        'T.B.............',
        'T.........G.....',
        'T...............',
        'T...,,,........T',
        'T...,,,....R...T',
        'T..............T',
        'T..............T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
    '1,2': {
      name: "Moat Meadow",
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T.~~~~~~~~~~~~.T',
        'T.~~~~~~~~~~~~.T',
        'T..............T',
        'T....G.........T',
        'T..............T',
        '................',
        '..B.....,,....B.',
        '........,,......',
        '..........G.....',
        'T..............T',
        'T...R.......R..T',
        'T..............T',
        'T..............T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
    '2,2': {
      name: "Thicket Edge",
      rows: [
        'TTTTTT....TTTTTT',
        'T..............T',
        'T...TT....G....T',
        'T...TT.........T',
        'T..............T',
        'T.........B....T',
        '...............T',
        '.....G.........T',
        '...............T',
        '..R.......,,,..T',
        'T.........,,,..T',
        'T..............T',
        'T...B....TTTT..T',
        'T........TTTT..T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
  },
});

registerArea({
  id: 'v1',
  name: 'Mossbrook',
  kind: 'town',
  tileset: 'town',
  lighting: 'day',
  music: 'village',
  screen: [16, 16],
  origin: [9, 3],
  start: [1, 2],
  screens: {
    '0,0': {
      name: "Orchard Row",
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T.T.T.T.T.T....T',
        'T.........,,...T',
        'T.T.T.T.T.T....T',
        'T........HHH...T',
        'T.T.T.T..HhH...T',
        'T........pp.....',
        'T........pppppp.',
        'T.,,,....pp.....',
        'T.,,,....pp.....',
        'T........pp....T',
        'T.f.f.f..pp....T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '1,0': {
      name: "Chapel Green",
      spawnsAt: {
        '10,5': { type: 'npc', name: 'Sister Anwe', palette: { tunic: 0xd8d0c0, tunicLight: 0xf0e8d8, cap: 0xd8d0c0 }, lines: ['The graves here are quiet. The barrow is not.'] },
      },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T....HHHHHH....T',
        'T....HHHHHH....T',
        'T....HHHhHH....T',
        'T.......pp.....T',
        'T.g.g...pp..,,.T',
        '........pp..,,..',
        '..g.g..pppp.....',
        'pppppppppppppppp',
        'pppppppppppppppp',
        'T.....pppp.....T',
        'T.,,..pppp..v.vT',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '2,0': {
      name: "Hill Farm",
      spawnsAt: {
        '11,6': { type: 'npc', name: 'Farmer Dobb', palette: { tunic: 0x8a6a3a, tunicLight: 0xaa8a5a, cap: 0xc8b070 }, lines: ['The pots by my door? Break them if you like. My wife will not.'] },
      },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T.ffffffff.....T',
        'T.f,,,,,,f..HHHT',
        'T.f,,,,,,f..HhHT',
        'T.f......f.....T',
        'T.ffff.fff.....T',
        '...............T',
        'ppppppp........T',
        'pppppppppp.....T',
        '.........p.....T',
        'T.B......p..v..T',
        'T........p.....T',
        'T........p.....T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '0,1': {
      name: "West Gate",
      spawnsAt: {
        '12,8': { type: 'npc', name: 'Rook', palette: { tunic: 0x7a5a8a, tunicLight: 0x9a7aaa }, lines: ['West is Barrowfield. Take the road and keep south.'] },
      },
      rows: [
        'TTTTTTppppTTTTTT',
        'T.TT..pppp..HHHT',
        'T.T...pppp..HhHT',
        'T.....pppp.....T',
        'T.f.f.pppp.....T',
        'T.....pppp..,,.T',
        'pppppppppppppppp',
        'pppppppppppppppp',
        '......pppp......',
        '..,,..pppp..v...',
        'T.....pppp.....T',
        'T.HHH.pppp.,,,.T',
        'T.HhH.pppp.....T',
        'T.....pppp..T..T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '1,1': {
      name: "Mossbrook Square",
      spawnsAt: {
        '5,4': { type: 'npc-shop', shop: 'v1-shop' },
        '10,4': { type: 'npc-smith' },
        '13,5': { type: 'npc-inventor' }, // the Sprint Boots (gameplay spec: the inventor in V1, before D1)
        '5,11': { type: 'npc-inn', inn: 'inn-1' },
        '10,11': { type: 'npc', name: 'Hettie', lines: ['Welcome to Mossbrook!', 'The inn lets you rest and wakes you there if you fall.'] },
        '2,8': { type: 'npc', name: 'Pip', personality: 'cheery', palette: { tunic: 0x4a9a5a, tunicLight: 0x6aba7a, hair: 0xd8a040, cap: 0xd05a3a }, lines: ['I am Pip! I can run faster than a slime. Probably.'] },
        '13,9': { type: 'npc', name: 'Old Tobin', personality: 'grumpy', palette: { tunic: 0x5a5a6a, tunicLight: 0x7a7a8a, hair: 0xc8c8c8, cap: 0x3a3a44 }, lines: ['Another adventurer. Wonderful.', 'Stay off my bench.'] },
        '5,14': { type: 'npc', name: 'Nell', personality: 'gossip', palette: { tunic: 0xa04a7a, tunicLight: 0xc06a9a, hair: 0x3a2418, cap: 0xe8d8b0 }, lines: ['Oh! You must be the one the king sent for!', 'Everyone is talking about you. Well, I am.'] },
        '12,14': { type: 'npc', name: 'Rowan', personality: 'worker', palette: { tunic: 0x7a5a3a, tunicLight: 0x9a7a5a, hair: 0x8a3a20, cap: 0x5a7a3a }, lines: ['Mind the fence posts, I just set them.'] },
      },
      rows: [
        'TTTTTTppppTTTTTT',
        'THHHHH.pp.HHHHHT',
        'THHHHH.pp.HHHHHT',
        'THHhHH.pp.HHhHHT',
        'T..pp..pp..pp..T',
        'T..pppppppppp..T',
        'ppppppp~~ppppppp',
        'pppppp~~~~pppppp',
        'pppppp~~~~pppppp',
        'ppppppp~~ppppppp',
        'T..pppppppppp..T',
        'T..pp..pp..pp..T',
        'THHhH..pp..HhHHT',
        'THHHH..pp..HHHHT',
        'T......pp......T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '2,1': {
      name: "Mill Pond",
      rows: [
        'TTTTTTppppTTTTTT',
        'T......pp......T',
        'T..~~~~........T',
        'T.~~~~~~~...HHHT',
        'T.~~~~~~~...HhHT',
        'T..~~~~~.......T',
        'ppppppp........T',
        'pppppppppppp...T',
        '...........p...T',
        '..,,,......p...T',
        'T.,,,..v...p...T',
        'T..........p...T',
        'T.T........p...T',
        'T..........pp..T',
        'T.....ppppppp..T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '0,2': {
      name: "Well Corner",
      rows: [
        'TTTTTTppppTTTTTT',
        'T.....pppp.....T',
        'T.HHH.pppp.....T',
        'T.HhH.pppp..,,.T',
        'T.....pppp.....T',
        'T.,,..pppp.....T',
        'T.....pppppppppp',
        'T.....pppppppppp',
        'T.R.............',
        'T......B........',
        'T.T............T',
        'T......,,,.....T',
        'T.B............T',
        'T..............T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
    '1,2': {
      name: "Mossbrook Lane",
      spawnsAt: {
        '3,8': { type: 'npc', name: 'Tam', palette: { tunic: 0x4a7a4a, tunicLight: 0x6a9a6a }, lines: ['Cut the bushes! Sometimes there are coins under them.'] },
        '13,4': { type: 'npc', name: 'Old Wick', lines: ['They say the barrow west of here keeps a throwing blade', 'that comes back to your hand.'] },
      },
      rows: [
        'TTTTTTppppTTTTTT',
        'THHHH.pppp.HHHHT',
        'THHhH.pppp.HhHHT',
        'T.....pppp.....T',
        'T.v...pppp...v.T',
        'T.....pppp.....T',
        'pppppppppppppppp',
        'pppppppppppppppp',
        '......pppp......',
        '.HHH..pppp..HHH.',
        'THhH..pppp..HhHT',
        'T.,...pppp...,.T',
        'T.f...pppp...f.T',
        'T.f..ipppp...f.T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '2,2': {
      name: "Lane End",
      rows: [
        'TTTTTTppppTTTTTT',
        'T.....pppp.....T',
        'T.,,..pppp..HHHT',
        'T.....pppp..HhHT',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'pppppppppp.....T',
        'pppppppppp.....T',
        '...............T',
        '..f.f.f........T',
        'T...........B..T',
        'T.,,,..........T',
        'T........TT....T',
        'T....v.........T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
  },
});

registerArea({
  id: 'ow-3-2',
  name: 'Barrowfield',
  kind: 'overworld',
  tileset: 'town',
  lighting: 'day',
  music: 'overworld',
  screen: [16, 16],
  origin: [6, 3],
  start: [2, 1],
  spawns: { G: field(['hopper', 'blob', 'buzzer']) },
  screens: {
    '0,0': {
      name: "Cliff Hollow",
      warps: { D: { area: 'cave-barrow', screen: [0, 0], x: 6, z: 7.4, yaw: Math.PI } },
      spawns: { G: field(['leaper', 'hopper'], [1, 2], { rare: ['treasure-slime'] }) },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T.2222222222...T',
        'T.2222222222...T',
        'T.##########...T',
        'T.####D#####...T',
        'T......p.......T',
        'T..R...p...G....',
        'T......pp.......',
        'T.G.....pppppppp',
        'T........ppppppp',
        'T.B............T',
        'T.....pppp..R..T',
        'T.....pppp.....T',
        'T.T...pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '1,0': {
      name: "Buzzing Heath",
      spawns: { G: field(['buzzer', 'buzzer', 'hopper'], [1, 2]) },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T.T..........T.T',
        'T...G..........T',
        'T......,,,.....T',
        'T.R....,,,...G.T',
        'T..............T',
        '................',
        'pppppppppppppppp',
        'pppppppppppppppp',
        '......pppp......',
        'T.B...pppp..B..T',
        'T.....pppp.....T',
        'T.G...pppp.....T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '2,0': {
      name: "Stump Wood",
      spawns: { G: field(['stump', 'stump', 'blob'], [1, 2]) },
      rows: [
        'TTTTTTTTTTTTTTTT',
        'T.T.T.T.T.T.T..T',
        'T..............T',
        'T.T...G...T.T..T',
        'T.........T....T',
        'T.T.T.T........T',
        '...............T',
        'ppppppp....G...T',
        'pppppppp.......T',
        '......ppp..T.T.T',
        'T.T....ppp.....T',
        'T.......ppp....T',
        'T.G......pp....T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '0,1': {
      name: "Leaper Hollow",
      spawns: { G: field(['leaper', 'blob-blue'], [1, 2]) },
      rows: [
        'TTTTTTppppTTTTTT',
        'T.TT..pppp.....T',
        'T.T...pppp..R..T',
        'T.....pppp.....T',
        'T.R.....G......T',
        'T............G.T',
        'T........ppppppp',
        'T......ppppppppp',
        'T.G....pp.......',
        'T......pp.......',
        'T.TT...pp...R..T',
        'T......pp......T',
        'T..R...pp....T.T',
        'T.....pppp.....T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '1,1': {
      name: "Barrow Crossing",
      rows: [
        'TTTTTTppppTTTTTT',
        'T.T...pppp...T.T',
        'T.....pppp.....T',
        'T.R...pppp..G..T',
        'T.....pppp.....T',
        'T.G...pppp.....T',
        'pppppppppppppppp',
        'pppppppppppppppp',
        '......pppp......',
        '..B...pppp..R...',
        'T.....pppp.....T',
        'T.,,..pppp..G..T',
        'T.....pppp.....T',
        'T.T...pppp...T.T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '2,1': {
      name: "Barrow Road",
      rows: [
        'TTTTTTppppTTTTTT',
        'T.T...pppp...T.T',
        'T.TT..pppp.....T',
        'T.....pppp..R..T',
        'T.G...pppp.....T',
        'T.....pppp...G.T',
        'pppppppppppppppp',
        'pppppppppppppppp',
        '................',
        '..R.....B.......',
        'T.........G....T',
        'T..B...........T',
        'T.........TT...T',
        'T....,,...TT...T',
        'T.....pppp.....T',
        'TTTTTTppppTTTTTT',
      ],
    },
    '0,2': {
      name: "Archer Ridge",
      spawns: { G: field(['archer', 'hopper'], [1, 2]) },
      rows: [
        'TTTTTTppppTTTTTT',
        'T.....pppp.....T',
        'T.#####.pp.....T',
        'T.#####.pp..G..T',
        'T.......pp.....T',
        'T.G.....pp.....T',
        'T.......pppppppp',
        'T.......pppppppp',
        'T.R.............',
        'T.........G.....',
        'T...B..........T',
        'T.........R....T',
        'T.T............T',
        'T......B.......T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
    '1,2': {
      name: "The Old Barrow",
      warps: { D: D1_ENTRANCE },
      spawns: {},
      spawnsAt: { '12,10': { type: 'npc', name: 'Warden Cray', palette: { tunic: 0x5a6a4a, tunicLight: 0x7a8a6a }, lines: ['That door opened on its own a week ago.', 'Small keys you find in there open only doors in there.'] } },
      rows: [
        'TTTTTTppppTTTTTT',
        'T.T...pppp...T.T',
        'T.....pppp.....T',
        'T.T.#######....T',
        'T...#22222##...T',
        'T..##222222#.T.T',
        '...#########....',
        '...####DD###....',
        '.....pppp.......',
        '..R.pppppp..R...',
        'T......pp......T',
        'T.T....pp....T.T',
        'T..R...pp......T',
        'T......pp......T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
    '2,2': {
      name: "Barrow Meadow",
      spawns: { G: field(['blob', 'buzzer'], [1, 2], { rare: ['treasure-slime'] }) },
      chests: { '8,11': 'heart-piece' },
      rows: [
        'TTTTTTppppTTTTTT',
        'T.....pppp.....T',
        'T.,,..pppp.....T',
        'T.....pppp..G..T',
        'T.R...pppp.....T',
        'T.....pppp.....T',
        'pppppppppp.....T',
        'pppppppppp.....T',
        '..........B....T',
        '..G............T',
        'T......BBB.....T',
        'T......BCB.....T',
        'T......BBB..R..T',
        'T..............T',
        'T..............T',
        'TTTTTTTTTTTTTTTT',
      ],
    },
  },
});

// The secret under Cliff Hollow: one small cave room (interior column 300).
registerArea({
  id: 'cave-barrow',
  name: 'Hollow Cave',
  kind: 'cave',
  tileset: 'dungeon',
  lighting: 'crypt',
  camera: 'interior',
  rooms: true,
  screen: [12, 9],
  at: [300 * 16, 0],
  warps: { X: { area: 'ow-3-2', screen: [0, 0], x: 6.5, z: 5.6, yaw: 0 } },
  screens: {
    '0,0': {
      name: 'Hollow Cave',
      chest: 'heart-piece',
      rows: [
        'WWWWWWWWWWWW',
        'W..........W',
        'W..S....S..W',
        'W..........W',
        'W....c.....W',
        'W..........W',
        'W..F....F..W',
        'W..........W',
        'WWWWWXXWWWWW',
      ],
    },
  },
});

registerPlace({ id: 'castle', name: 'Crownhold Castle', kind: 'castle', order: 10, spot: CASTLE_START });
registerPlace({ id: 'v1', name: 'Mossbrook', kind: 'village', order: 20, spot: { area: 'v1', screen: [1, 2], x: 8, z: 12, yaw: Math.PI } });
registerPlace({ id: 'inn-1', name: 'The Mossy Kettle', kind: 'inn', order: 21, spot: { area: 'v1', screen: [1, 1], x: 5.5, z: 10, yaw: 0 } });
registerPlace({ id: 'cave-barrow', name: 'Hollow Cave', kind: 'cave', order: 60, spot: { area: 'ow-3-2', screen: [0, 0], x: 6.5, z: 5.6, yaw: 0 }, area: 'cave-barrow' });
registerPrologue({ spot: CASTLE_START });
