export const description = 'The Last Departure: real station edge travel, native young Tern conversation, guarded past repair, courier sword/flank/hook/pot/volley/dodge/shield/Shelter inputs, physical bridge/chest, consent, once-only homecoming, town lights and reload. Engine/workshop milestones, sword, equipment, health, positions and isolated courier HP/AI resets are disclosed fixtures. All audio stays muted.';
export default async function(t) {
 const flag=id=>t.eval(id=>window.__voxelHeroes.game.state.hasFlag(id),id);
 const place=(x,z,f='north')=>t.eval(([x,z,f])=>{const h=window.__voxelHeroes;h.game.hero.hero.place(x,z);h.game.hero.hero.setFacing(f);h.player.lockT=h.player.knockT=h.player.stallT=0;},[x,z,f]);
 const view=()=>t.eval(()=>{const h=window.__voxelHeroes,e=h.entities.find(e=>e.type==='bell-courier'&&!e.removed);return{hp:h.state.hp,magic:h.state.magic,maxMagic:h.state.maxMagic,foe:e?{hp:e.hp,...e.ai.departure,pose:e.mesh.pose,cue:e.cue.visible}:null,shots:h.entities.filter(e=>e.type==='departure-bolt'&&!e.removed).length,mode:h.state.mode};});
 const dismiss=()=>t.eval(async()=>{const h=window.__voxelHeroes;for(let i=0;i<1500&&h.state.mode==='dialog';i++){h.input.tap('confirm');await h.tick();}await h.step(.4);});
 const photo=async name=>{await t.page.waitForFunction(()=>!window.__voxelHeroes.game.banner.bannerView().visible);await t.eval(()=>{window.__voxelHeroes.player.hero.root.visible=true;});await t.shot(name);};
 const interact=async(x,z)=>{await place(x,z);await t.tap('sword');};
 await t.eval(()=>{const h=window.__voxelHeroes;h.game.progress.startNewGame({prologue:false});h.game.audio.setMuted(true);h.game.audio.setVolumes({master:0});h.game.settings.setSetting('npcVoices',false);h.give('blade-start');h.game.swords.equipSword('blade-start');h.player.invT=999;});
 await t.teleport('mossbrook-future:1,0',8.5,14.5);await t.stick(0,1,.75);await t.step(.7);
 t.expect((await t.state()).key==='mossbrook-future:1,1','actual movement takes the Silent Year copperwalk south to the Last Platform');
 t.expect(await t.eval(()=>{const h=window.__voxelHeroes,s=h.screen();return h.world.tile(s.x0+7,s.z0+9)==='~'&&h.world.tile(s.x0+2,s.z0+5)==='Z';}),'the unpowered future has a flooded platform and dark native station lights');await photo('01-the-waiting-platform');
 await place(11.5,13.3);await t.stick(0,-1,.3);
 t.expect(!await flag('era:departure-tag'),'physical chest contact cannot skip repairing the past signal');
 await place(14.5,14.3,'east');await t.stick(1,0,.5);
 t.expect((await t.state()).key==='mossbrook-future:1,1'&&(await t.state()).lx<14.7,'the native low rail keeps the lower platform collision boundary intact');
 await t.teleport('mossbrook-past:1,0',8.5,14.5);await t.stick(0,1,.75);await t.step(.7);
 t.expect((await t.state()).key==='mossbrook-past:1,1','actual movement takes the First Bloom copperwalk south to Tern first spring');
 await interact(4.5,5.6);t.expect((await view()).mode==='dialog','actual Talk input opens young Tern first-day conversation');await t.tap('confirm');await photo('02-terns-first-day');await dismiss();
 t.expect(await flag('era:departure'),'young Tern starts the original station story');
 await t.eval(()=>window.__voxelHeroes.game.objective.trackQuest('last-departure'));
 t.expect(await t.eval(()=>/north.*west.*engine/i.test(window.__voxelHeroes.game.objective.objectiveText())),'the station journal pin routes north then west to the actual missing engine');
 await interact(6.5,5.6);t.expect(!await flag('era:departure-powered'),'actual regulator input cannot repair without engine and workshop pressure');
 await t.eval(()=>window.__voxelHeroes.game.state.setFlag('era:water-restored'));
 t.expect(await t.eval(()=>/north.*east.*workshop/i.test(window.__voxelHeroes.game.objective.objectiveText())),'after engine repair the station pin routes north then east to the workshop');
 await t.eval(()=>window.__voxelHeroes.game.state.setFlag('era:archive-powered'));
 await interact(6.5,5.6);t.expect(!await flag('era:departure-powered'),'living native station thieves keep the repair unavailable');
 t.expect((await t.fight({heal:20,seconds:90})).kills===2,'real sword combat defeats both past station thieves');await t.step(.6);
 await interact(6.5,5.6);await dismiss();
 t.expect(await flag('era:departure-powered'),'actual cleared-platform regulator interaction repairs the past signal');
 t.expect(await t.eval(()=>{const h=window.__voxelHeroes,s=h.screen();return h.world.tile(s.x0+6,s.z0+4)==='J';}),'the repaired native regulator keeps a lit interactive inscription');await photo('03-leave-a-lamp');
 const partial=await t.save();await t.load(partial);await t.step(.5);
 t.expect(await flag('era:departure-powered')&&!(await t.state()).enemies,'partial reload retains the repaired signal and defeated one-time thieves');
 await t.teleport('mossbrook-future:1,1',8.5,7.2);await t.step(1.7);
 t.expect(await t.eval(()=>{const h=window.__voxelHeroes,s=h.screen();return [8,9,10].every(z=>[7,8].every(x=>h.world.tile(s.x0+x,s.z0+z)==='j'))&&[[2,5],[10,5],[3,10],[12,10]].every(([x,z])=>h.world.tile(s.x0+x,s.z0+z)==='Y');}),'the past repair grows the full six-tile bridge and lights all four future station lamps');await photo('04-a-path-through-tomorrow');
 await place(11.5,13.3);await t.stick(0,-1,.3);t.expect(!await flag('era:departure-tag'),'the powered chest still waits for the living bell courier');
 await t.eval(()=>{const h=window.__voxelHeroes,e=h.entities.find(e=>e.type==='bell-courier');window.__departureThink=e.think;});
 const reset=()=>t.eval(()=>{const h=window.__voxelHeroes,s=h.screen(),e=h.entities.find(e=>e.type==='bell-courier');for(const p of h.entities)if(p.kind==='projectile'||p.kind==='pickup')p.remove();e.x=s.x0+8.5;e.z=s.z0+4.5;e.yaw=0;e.holder.rotation.y=0;e.hp=24;e.stunT=e.knockT=0;e.kx=e.kz=0;e.hitSwing=-1;e.ai.departure={phase:'wait',t:999,dx:0,dz:1,shots:0,openT:0,volleys:0};e.think=()=>{};e.harmless=true;e.present();h.player.invT=999;h.setHp(h.state.maxHp);});
 await reset();await place(8.5,6);await t.tap('sword');await t.step(.5);
 t.expect((await view()).foe.hp===24,'actual frontal sword input cannot pass the closed courier shutters');
 await place(8.5,3,'south');await t.tap('sword');await t.step(.5);
 t.expect((await view()).foe.hp<24,'actual sword input rewards flanking the locked attack facing');
 await reset();await t.give('grapple');await t.eval(()=>window.__voxelHeroes.game.inventory.selectItem('grapple'));await place(8.5,7);await t.tap('item');await t.step(.3);
 t.expect((await view()).foe.hp===24&&(await view()).foe.openT>2.5,'the actual zero-damage grapple opens the courier for three seconds');await photo('05-open-the-old-shutters');
 await place(8.5,6);await t.tap('sword');await t.step(.5);t.expect((await view()).foe.hp<24,'a real sword punishes the grapple opening');await t.step(3.5);
 t.expect((await view()).foe.openT===0,'the tool opening expires normally');
 await reset();await place(11.5,7.6);await t.tap('sword');t.expect(await t.eval(()=>!!window.__voxelHeroes.player.carrying),'real sword-button input lifts native platform pottery');
 await place(8.5,6.5);await t.eval(()=>{const e=window.__voxelHeroes.entities.find(e=>e.type==='bell-courier');e.ai.departure.phase='call';e.ai.departure.t=1;e.present();});await t.tap('sword');await t.step(.35);
 t.expect((await view()).foe.openT>2&&(await view()).foe.phase==='recover'&&(await view()).shots===0,'a real thrown pot cancels the pending notes and opens the shutters');await photo('06-pottery-breaks-the-call');
 await reset();await place(8.5,7.3);await t.eval(()=>{const h=window.__voxelHeroes,e=h.entities.find(e=>e.type==='bell-courier');e.think=window.__departureThink;e.ai.departure.t=0;h.player.invT=0;});await t.step(.05);
 t.expect((await view()).foe.phase==='call'&&(await view()).foe.cue&&(await view()).shots===0,'the real courier clock warns three committed note lanes before firing');await photo('07-three-notes');
 const hp=(await view()).hp;await t.stick(1,0,.45);await t.step(.95);
 t.expect((await view()).foe.volleys===1&&(await view()).foe.phase==='recover'&&(await view()).foe.pose==='open','the natural three-note volley exposes the native courier core');
 await t.step(.7);t.expect((await view()).hp===hp,'actual sideways movement evades the committed fan');
 await reset();await place(8.5,7.3);await t.eval(()=>{const h=window.__voxelHeroes,e=h.entities.find(e=>e.type==='bell-courier');e.hp=12;e.think=window.__departureThink;e.ai.departure.t=0;});await t.step(.02);
 t.expect((await view()).foe.phase==='call'&&(await view()).foe.t>.72&&(await view()).foe.t<=.75,'the disclosed half-health fixture starts the faster three-quarter-second warning');
 await t.step(.65);t.expect((await view()).shots===0,'the faster warning still gives time before the first live note');
 await t.step(.56);t.expect((await view()).foe.volleys===1&&(await view()).foe.phase==='recover'&&(await view()).foe.t<1.8,'the wounded native courier fires three notes then exposes its shorter recovery');
 await reset();await place(8.5,7.3);await t.eval(()=>{const h=window.__voxelHeroes,e=h.entities.find(e=>e.type==='bell-courier');e.think=window.__departureThink;e.ai.departure.t=0;h.state.gear.shield=1;h.player.invT=0;h.input.down('guard');});await t.step(2);
 t.expect((await view()).hp===hp,'an actual held tier-one shield blocks the station notes');await t.eval(()=>window.__voxelHeroes.input.up('guard'));
 await reset();await place(8.5,7.3);await t.eval(()=>{const h=window.__voxelHeroes;for(const flag of['era:voices-returned','era:copper-memory','era:tern-travels'])h.game.state.setFlag(flag);h.state.maxMagic=h.state.magic=5;h.state.gear.shield=0;});await t.step(.4);
 await t.page.keyboard.down('Shift');await t.step(.02);await t.tap('sword');await t.page.keyboard.up('Shift');
 t.expect((await view()).magic===3&&await t.eval(()=>window.__voxelHeroes.game.companions.companionView().wardT)>2.8,'actual Guard plus Sword spends two personal magic on Tern Bell Shelter');
 await t.eval(()=>{const h=window.__voxelHeroes,e=h.entities.find(e=>e.type==='bell-courier');e.think=window.__departureThink;e.ai.departure.t=0;h.player.invT=0;});await t.step(2);
 t.expect((await view()).hp===hp&&await t.eval(()=>window.__voxelHeroes.game.companions.companionView().blocks)>0,'the real incoming station notes are sheltered even without a shield');await photo('08-tern-keeps-his-promise');
 await reset();await place(8.5,7);await t.tap('item');await t.step(.3);await place(8.5,6);
 for(let i=0;i<12&&(await view()).foe;i++){await t.tap('sword');await t.step(.5);}
 t.expect(!(await view()).foe,'actual hook and sword inputs finish the courier encounter');
 await t.walkTo(8.5,11.5);t.expect((await t.state()).lz>11,'actual movement crosses the bridge built by the past signal');
 await t.walkTo(11.5,13.5);await t.stick(0,-1,.4);await t.step(.1);
 t.expect(await flag('era:departure-tag'),'the native departure chest awards its physical passenger tag');await photo('09-one-passenger');await dismiss();
 const before=(await view()).maxMagic;await t.walkTo(3.5,5.5);await t.tap('sword');await t.step(.1);
 t.expect((await view()).mode==='dialog','actual signal input asks consent before calling the courier home');
 await t.eval(async()=>{const h=window.__voxelHeroes;for(let i=0;i<1500;i++){const d=h.game.dialog.dialogView();if(!d?.choices){h.input.tap('confirm');await h.tick();continue;}h.render();h.game.ui.pressUi('dialog-choice-1');await h.tick();break;}});
 t.expect(!await flag('era:departure-home')&&(await view()).maxMagic===before,'the real Let me think choice preserves both the tag and unfinished story');
 await t.tap('sword');await dismiss();
 t.expect(await flag('era:departure-home')&&(await view()).maxMagic===before+1,'actual affirmative choice grants exactly one permanent magic gem');
 t.expect(await t.eval(()=>window.__voxelHeroes.game.objective.trackedQuestId())===null,'the shared homecoming releases the completed personal journal pin');
 await t.step(1.5);await t.tap('sword');await dismiss();t.expect((await view()).maxMagic===before+1,'repeating the native station conversation cannot duplicate the chime');
 await t.teleport('v1:1,1',12.5,11.5);await t.step(.4);
 t.expect(await t.eval(()=>{const h=window.__voxelHeroes,s=h.screen();return [[13,10],[14,10],[13,11]].every(([x,z])=>h.world.tile(s.x0+x,s.z0+z)==='Y');}),'the completed story leaves all three new station lights in present-day Mossbrook');await photo('10-a-light-for-the-next-person');
 const save=await t.save();await t.load(save);await t.step(.4);
 t.expect((await view()).maxMagic===before+1&&await flag('era:departure-home'),'reload preserves the homecoming and permanent reward');
 await t.teleport('mossbrook-future:1,1',3.5,5.5);await t.step(.4);await t.tap('sword');await dismiss();
 t.expect(!(await view()).foe&&(await view()).maxMagic===before+1,'returning after reload preserves the defeated courier and never repeats the reward');
 t.expect(await t.eval(()=>window.__voxelHeroes.game.objective.questEntries().find(e=>e.id==='last-departure').status)==='done','the journal retains the original companion story as completed');
}
