export const description = 'Muted native Keeper Mara recruitment after a real shore beacon, three distinct companions, actual walking, keyboard Steamwheel fire damage/cost/cooldown, wall and range boundaries, locked/carrying/wrong-tool/no-partner gates, idle safety, save/load and real dismissal/rejoin. Prior lens, archive, magic capacity, combat positions and stationary foes are disclosed fixtures.';
export default async function(t) {
  const view=()=>t.eval(()=>window.__voxelHeroes.game.companions.companionView());
  const shot=async n=>{await t.eval(()=>window.__voxelHeroes.player.hero.root.visible=true);await t.shot(n);};
  const answer=choice=>t.eval(async choice=>{const h=window.__voxelHeroes;for(let i=0;i<2000&&h.state.mode==='dialog';i++){const d=h.game.dialog.dialogView();if(d.choices&&d.page===d.pages-1)h.input.tap(d.choice===choice?'confirm':'down');else if(i%15===0)h.input.tap('confirm');await h.tick();}return h.state.mode;},choice);
  const talk=async type=>{await t.eval(type=>{const h=window.__voxelHeroes,s=h.screen(),e=h.entities.find(e=>e.type===type&&!e.removed&&e.object.visible);h.game.hero.hero.place(e.x-s.x0,e.z-s.z0+1);h.game.hero.hero.setFacing('north');},type);await t.tap('sword');t.expect((await t.state()).mode==='dialog',`actual Talk opens ${type}`);t.expect(await t.eval(()=>window.__voxelHeroes.game.dialog.dialogView().speaker)===(type==='npc-mira'?'Mira':'Keeper Mara'),`facing ${type} opens the intended speaker among nearby people`);};
  const cast=async()=>{await t.page.keyboard.down('Shift');await t.step(1/60);await t.page.keyboard.down('k');await t.step(1/60);await t.page.keyboard.up('k');await t.page.keyboard.up('Shift');await t.step(1/60);};
  await t.eval(()=>{const h=window.__voxelHeroes;h.game.audio.setMuted(true);h.game.audio.setVolumes({master:0});h.game.settings.setSetting('npcVoices',false);});
  await t.press('Enter');await t.step(1.1);
  t.expect(await t.eval(()=>!window.__voxelHeroes.game.companions.setMaraTravelling(true))&&!(await view()).maraRecruited,'Mara cannot leave an unlit shore');
  await talk('npc-mira');await answer(0);await t.step(.2);
  await t.teleport('tidecoast:0,1',5.5,10.5);await t.step(.2);await t.eval(()=>{for(const e of window.__voxelHeroes.entities)if(e.kind==='enemy')e.remove();});
  await talk('npc-mara');await shot('01-keeper-at-her-post');
  t.expect(await t.eval(()=>!window.__voxelHeroes.game.dialog.dialogView().choices),'the shore keeper offers a story and clue before recruitment unlocks');
  await answer(0);t.expect(!(await view()).maraRecruited,'the early conversation does not recruit or bypass the beacon');
  await t.give('fire-wand');await t.give('ember-lens');await t.teleport('tidecoast:0,2',8.5,10.5);await t.eval(()=>{const h=window.__voxelHeroes;h.game.hero.hero.setFacing('north');h.game.inventory.selectItem('fire-wand');});
  await t.tap('item');await t.step(1);await t.tap('item');await t.step(.7);
  t.expect(await t.eval(()=>window.__voxelHeroes.state.flags.has('coast:beacon-lit')),'two real wand shots thaw the seal and light the keeper beacon');
  await shot('02-light-for-tomorrow');await t.teleport('tidecoast:0,1',5.5,10.5);await t.step(.2);await t.eval(()=>{for(const e of window.__voxelHeroes.entities)if(e.kind==='enemy')e.remove();});
  await talk('npc-mara');await shot('03-mara-recruitment');await answer(0);await t.step(.3);
  t.expect((await view()).maraRecruited&&(await view()).mara.visible,'Travel with Mara recruits the actual keeper after the light is restored');
  t.expect(await t.eval(()=>window.__voxelHeroes.entities.filter(e=>e.type==='npc-mara').every(e=>!e.out&&!e.solid&&!e.object.visible)),'her resident presentation and collider disappear while travelling');
  await t.eval(()=>{const h=window.__voxelHeroes;h.game.state.setFlag('era:voices-returned');h.game.grants.grant('copper-memory',1,{fanfare:false});h.game.companions.setTernTravelling(true);h.state.maxMagic=9;h.state.magic=9;});
  await t.teleport('Crossroads',8,5.5);await t.step(.3);await t.eval(()=>{for(const e of window.__voxelHeroes.entities)if(e.kind==='enemy')e.remove();});
  await t.walkTo(6.5,5.5);await t.walkTo(6.5,7.5);await t.step(.5);
  let v=await view();
  t.expect(v.mira.visible&&v.tern.visible&&v.mara.visible&&!v.mira.blocked&&!v.tern.blocked&&!v.mara.blocked,'all three companions follow actual walking on safe ground');
  t.expect(await t.eval(()=>window.__voxelHeroes.entities.filter(e=>e.kind==='companion'&&!e.removed).length)===3,'there is exactly one Mira, Tern and Mara');
  t.expect(v.steamUnlocked&&v.steamReady,'the recruited pair and selected wand unlock Steamwheel');await shot('04-three-companions');
  await t.teleport('d4:0,7',7.5,8.5);await t.step(1.6);
  await t.eval(()=>{const h=window.__voxelHeroes,s=h.screen(),es=h.entities.filter(e=>e.type==='tideglass-skater');for(const[e,x]of es.map((e,i)=>[e,i?9.5:5.5])){e.x=s.x0+x;e.z=s.z0+6.5;e.hp=18;e.think=()=>{};e.harmless=true;}h.player.invT=999;h.state.magic=9;});
  await t.step(.2);t.expect((await view()).steamReady,'the party can combine techniques in an active combat room');
  await cast();v=await view();
  t.expect(v.steamCount===1&&await t.eval(()=>window.__voxelHeroes.state.magic)===6,'real Guard plus Item casts once and pays three personal magic');
  t.expect(v.steamCooldown>5.9&&v.steamT>.6,'Steamwheel starts its six-second recharge and visible pulse');
  t.expect(await t.eval(()=>window.__voxelHeroes.entities.filter(e=>e.type==='tideglass-skater').every(e=>e.hp===10&&e.ai.tide.openT>4.9&&e.mesh.pose==='open')),'one fire pulse deals eight to both nearby ice shells and opens them');
  t.expect(await t.eval(()=>!window.__voxelHeroes.entities.some(e=>e.type==='fire-bolt'&&!e.removed)),'the technique consumes Item so it does not also shoot a normal bolt');await t.step(.2);await shot('05-steamwheel-opens-two-shells');
  await cast();t.expect((await view()).steamCount===1&&await t.eval(()=>window.__voxelHeroes.state.magic)===6,'a repeat during cooldown cannot cast or spend another three gems');
  await t.step(6.2);await t.eval(()=>{const h=window.__voxelHeroes;h.state.magic=2;for(const e of h.entities)if(e.type==='fire-bolt')e.remove();});await cast();
  t.expect((await view()).steamCount===1&&await t.eval(()=>window.__voxelHeroes.state.magic)===2,'two magic gems cannot buy a three-gem technique');
  await t.teleport('Crossroads',7.5,8.5);await t.step(.8);await t.eval(()=>{const h=window.__voxelHeroes;for(const e of h.entities)if(e.kind==='enemy')e.remove();h.state.magic=9;window.__maraUpdates=new Map();for(const[e,dx]of h.entities.filter(e=>e.kind==='companion'&&!e.removed).map((e,i)=>[e,(i-1)*.8])){window.__maraUpdates.set(e,e.update);e.update=()=>{};e.x=h.player.x+dx;e.z=h.player.z+1;e.object.visible=true;}h.state.companionRuntime.steamCooldown=0;});
  for(const [field,value,label]of[['lockT',1,'locked input'],['knockT',1,'knockback'],['stallT',1,'stalled action'],['carrying',{fixture:true},'carried pottery']]){
    await t.step(.7);await t.eval(([field,value])=>{const h=window.__voxelHeroes;h.player[field]=value;},[field,value]);await cast();t.expect((await view()).steamCount===1&&await t.eval(()=>window.__voxelHeroes.state.magic)===9,label+' prevents Steamwheel');await t.eval(field=>window.__voxelHeroes.player[field]=field==='carrying'?null:0,field);
  }
  await t.give('grapple');await t.eval(()=>window.__voxelHeroes.game.inventory.selectItem('grapple'));await cast();t.expect((await view()).steamCount===1,'selecting a different tool preserves its ordinary action');
  await t.step(.8);await t.eval(()=>{const h=window.__voxelHeroes;h.game.inventory.selectItem('fire-wand');h.game.state.clearFlag('era:mira-travels');});await cast();t.expect((await view()).steamCount===1,'Mara cannot cast the dual technique without Mira');
  await t.step(.8);await t.eval(()=>{const h=window.__voxelHeroes;h.game.state.setFlag('era:mira-travels');h.entities.find(e=>e.type==='companion-mara').x=h.player.x+4.5;});await cast();t.expect((await view()).steamCount===1,'a distant keeper cannot lend her technique');
  await t.step(.8);await t.eval(()=>{const h=window.__voxelHeroes,m=h.entities.find(e=>e.type==='companion-mara');m.x=h.player.x;m.z=h.player.z-2;h.world.setTile(Math.floor(h.player.x),Math.floor(h.player.z)-1,'#',{rebuild:true});});await cast();t.expect((await view()).steamCount===1,'a wall between keeper and caster blocks the combination');
  await t.eval(()=>{const h=window.__voxelHeroes;h.world.setTile(Math.floor(h.player.x),Math.floor(h.player.z)-1,'.',{rebuild:true});for(const[e,fn]of window.__maraUpdates)e.update=fn;});
  await t.teleport('d4:0,7',5.5,8.5);await t.step(1);
  await t.eval(()=>{const h=window.__voxelHeroes,s=h.screen(),es=h.entities.filter(e=>e.type==='tideglass-skater');es[0].x=s.x0+5.5;es[0].z=s.z0+5.5;es[1].x=s.x0+13.5;es[1].z=s.z0+8.5;for(const e of es){e.hp=18;e.ai.tide.openT=0;e.think=()=>{};e.harmless=true;}h.world.setTile(s.x0+5,s.z0+6,'W',{rebuild:true});h.state.magic=9;h.state.companionRuntime.steamCooldown=0;});
  await cast();t.expect((await view()).steamCount===2&&await t.eval(()=>window.__voxelHeroes.entities.filter(e=>e.type==='tideglass-skater').every(e=>e.hp===18)),'a valid cast cannot burn through a wall or reach the distant skater');await shot('06-steam-range-and-wall');
  await t.eval(()=>{const h=window.__voxelHeroes,s=h.screen();h.world.setTile(s.x0+5,s.z0+6,'e',{rebuild:true});});await t.step(6.2);
  t.expect(await t.eval(()=>window.__voxelHeroes.entities.filter(e=>e.type==='tideglass-skater').every(e=>e.hp===18)),'idle companions cannot damage or farm either foe');
  const saved=await t.save();await t.load(saved);await t.step(.4);v=await view();
  t.expect(v.recruited&&v.ternRecruited&&v.maraRecruited&&v.steamCooldown===0&&v.steamCount===0&&v.steamT===0,'save/load keeps all three recruitments and clears temporary technique timers');
  t.expect(await t.eval(()=>window.__voxelHeroes.entities.filter(e=>e.kind==='companion'&&!e.removed).length)===3,'reloading the party never duplicates a follower');
  await t.teleport('mossbrook-past:1,0',13.5,9.5);await t.step(.2);await t.hold('ArrowRight',.9);await t.step(1.1);
  t.expect((await t.state()).key==='mossbrook-past:2,0'&&(await view()).mara.visible&&!(await view()).mara.blocked,'Mara follows the real room edge into the First Bloom workshop');await shot('07-keeper-in-the-first-bloom');
  await t.teleport('v1:1,1',8,10);await t.step(.3);await talk('companion-mara');await answer(1);await t.step(.2);
  t.expect(!(await view()).maraRecruited&&!(await view()).mara.visible&&(await view()).mira.visible&&(await view()).tern.visible,'Keep the shore dismisses only Mara through a native choice');
  await t.teleport('tidecoast:0,1',5.5,10.5);await t.step(.3);await t.eval(()=>{for(const e of window.__voxelHeroes.entities)if(e.kind==='enemy')e.remove();});
  t.expect(await t.eval(()=>window.__voxelHeroes.entities.find(e=>e.type==='npc-mara')?.out),'the dismissed keeper returns to her shore post');await talk('npc-mara');await answer(0);await t.step(.2);t.expect((await view()).maraRecruited,'Mara rejoins without repeating the beacon reward');
  await t.eval(()=>window.__voxelHeroes.game.progress.startNewGame());await t.step(.2);v=await view();
  t.expect(!v.recruited&&!v.ternRecruited&&!v.maraRecruited&&!v.steamUnlocked&&v.steamT===0,'a new adventure clears all companions and Steamwheel');
}
