export const description='Four-orb entrance, 120-second reflection, three independent floor keys/maps/puzzles/rematches/rewards, Truesight/clone growth, lightning and shield/charge rules, two-stage final, ending/homecoming and saved completion. Earlier campaign, room kills, trial invulnerability and controlled boss windows are fixtures.';
export default async function(t){
 const photograph=t.shot;t.shot=async name=>{await t.eval(()=>window.__voxelHeroes.player.hero.root.visible=true);await t.page.waitForTimeout(2400);return photograph(name);};
 await t.eval(()=>{const h=window.__voxelHeroes;h.game.progress.startNewGame({name:'Bo',class:'balanced'});h.state.flags.add('overworld:talked:king');for(const id of ['d1','d2','d3','d4']){h.state.flags.add('dungeon:'+id+':entered');h.game.dungeons.giveBossKey(id);h.game.dungeons.defeatBoss(id);h.game.dungeons.completeDungeon(id);}h.state.flags.delete('orb:4');for(const id of['boomerang','bombs','grapple','fire-wand'])h.game.inventory.giveItem(id);for(const id of['spell-reveal','spell-reflect','spell-quake','spell-freeze'])h.game.spells.learnSpell(id);h.player.invT=999;});
 const safe=()=>t.eval(()=>{const h=window.__voxelHeroes;h.player.invT=999;h.setHp(h.state.maxHp);});
 const settle=async()=>{await t.step(1.6);await safe();};
 const answer=()=>t.eval(async()=>{const h=window.__voxelHeroes;let quiet=0;for(let i=0;i<600&&quiet<25;i++){if(i%20===0&&h.state.mode!=='play')h.input.tap('confirm');await h.tick();quiet=h.state.mode==='play'?quiet+1:0;}await h.step(1.6);});
 const kill=async()=>{await t.eval(()=>{for(const e of [...window.__voxelHeroes.entities])if(e.kind==='enemy'&&!e.removed&&e.countsForClear!==false)e.die();});await t.step(.25);};
 const go=async(dir,name)=>{if((await t.state()).screenName!==name)await t.exit(dir);await settle();t.expect((await t.state()).screenName===name,dir+' reaches '+name);};
 const chest=async(x,z)=>{await t.walkTo(x+.5,z+1.6);await t.stick(0,-1,.4);await settle();};
 const warp=async(x,z,key)=>{await t.walkTo(x+.5,z+.5,{allowHooks:true,soft:true});await settle();t.expect((await t.state()).key===key,'passage reaches '+key+' from '+(await t.state()).key);};
 const item=async(id,facing,time=.55)=>{await t.eval(([id,f])=>{const h=window.__voxelHeroes;h.game.inventory.selectItem(id);h.game.hero.hero.setFacing(f);},[id,facing]);await t.tap('item');await t.step(time);};
 const clearShots=()=>t.eval(()=>{for(const e of [...window.__voxelHeroes.entities])if(e.kind==='projectile'||e.type==='crown-wisp')e.remove();});
 await t.teleport('tidecoast:2,2',8.5,5);await kill();await item('fire-wand','north');
 await t.walkTo(8.5,2.5,{allowHooks:true,soft:true});await t.step(.3);t.expect((await t.state()).key==='tidecoast:2,2','three orbs cannot enter the real tower doorway');await t.shot('01-four-light-gate');
 await t.eval(()=>window.__voxelHeroes.state.flags.add('orb:4'));await t.walkTo(8.5,4.5);await warp(8,2,'tower-trial:0,0');await t.step(4);await safe();
 const blocked=await t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-bishop');const result=h.game.damage.dealDamage(b,{amount:10,source:'sword',from:h.player,truesight:true});return{hp:b.hp,result:result.result,copies:b.segments.length};});t.expect(blocked.hp===75&&blocked.result==='blocked'&&blocked.copies===2,'first meeting is invulnerable even to sight, with three total bodies');await t.shot('02-first-reflection');
 await t.step(121);await safe();t.expect(await t.eval(()=>window.__voxelHeroes.state.flags.has('tower:trial')&&!window.__voxelHeroes.entities.some(e=>e.type==='boss-bishop')),'120 real simulation seconds clear the first reflection and its copies');await warp(10,0,'tower-hive:1,2');
 await kill();await t.walkTo(8,7);t.expect(await t.eval(()=>window.__voxelHeroes.game.keys.keyCount('tower-hive'))===1,'amber patrol releases its own small key');
 await t.walkTo(3.5,9.8);await t.eval(()=>window.__voxelHeroes.game.hero.hero.setFacing('north'));await t.tap('sword');await answer();t.expect(await t.eval(()=>window.__voxelHeroes.game.inventory.hasItem('spell-truesight')),'Sage Iona teaches Truesight through actual conversation');await t.shot('03-truesight-sage');
 await go('west','The Resting Light');await chest(8,4);await t.tap('map');await t.shot('04-amber-map');await t.tap('map');
 await t.eval(()=>{const h=window.__voxelHeroes;h.setHp(2);h.state.magic=0;});await t.walkTo(4.5,8.5);await t.eval(()=>window.__voxelHeroes.game.hero.hero.setFacing('north'));await t.tap('sword');await t.step(.2);t.expect(await t.eval(()=>{const h=window.__voxelHeroes;return h.state.hp===h.state.maxHp&&h.state.magic===h.state.maxMagic;}),'real well interaction restores life and magic');await safe();
 await go('east','The Amber Memory');await t.walkTo(8,3);await t.stick(0,-1,.85);await go('north','The Amber Memory Gate');
 t.expect(await t.eval(()=>window.__voxelHeroes.game.keys.keyCount('tower-hive'))===0,'both leaves spend only one amber key');
 for(const x of[3.5,12.5]){await t.walkTo(x,3.2);await item('boomerang','north');}await go('west','The Memory Crown');await chest(8,4);await t.shot('05-amber-crown');await go('east','The Amber Memory Gate');await t.walkTo(8,2);await t.stick(0,-1,.85);await warp(7,0,'tower-hive-boss:0,0');await t.step(4);await safe();
 t.expect(await t.eval(()=>window.__voxelHeroes.entities.some(e=>e.type==='boss-queen'&&e.refight)),'first tower floor uses the harder queen rematch');await t.shot('06-amber-rematch');await kill();await t.step(.4);t.expect(await t.eval(()=>!window.__voxelHeroes.entities.some(e=>e.type==='heart-container')),'tower rematch gives no repeat permanent heart');await warp(10,0,'tower-hive:1,0');await chest(8,4);t.expect(await t.eval(()=>window.__voxelHeroes.state.gear.shield===6),'real floor reward grants the Bastion Shield');await t.shot('07-storm-shield');await warp(7,0,'tower-watch:1,2');
 await kill();await t.walkTo(8,7);t.expect(await t.eval(()=>window.__voxelHeroes.game.keys.keyCount('tower-watch'))===1,'sand key is separate from the spent amber key');await t.walkTo(8,3);await t.stick(0,-1,.85);await go('north','The Sand Memory Gate');await t.walkTo(4.5,7.5);await t.stick(1,0,4.5);await t.step(.4);await t.shot('08-sand-counterweight');await go('west','The Memory Crown');await chest(8,4);await go('east','The Sand Memory Gate');await t.walkTo(8,2);await t.stick(0,-1,.85);await warp(7,0,'tower-watch-boss:0,0');await t.step(4);await safe();
 t.expect(await t.eval(()=>window.__voxelHeroes.entities.some(e=>e.type==='boss-colossus'&&e.refight&&e.segments.length===4)),'second floor uses the multipart colossus rematch');await t.shot('09-sand-rematch');await kill();await warp(10,0,'tower-watch:1,0');await chest(8,4);t.expect(await t.eval(()=>window.__voxelHeroes.state.swords.owned.includes('blade-dawn')),'actual reward chest grants Dawn Blade');await t.eval(()=>window.__voxelHeroes.game.swords.equipSword('blade-dawn'));await t.shot('10-dawn-blade');await warp(7,0,'tower-tide:1,2');
 await kill();await t.walkTo(8,7);t.expect(await t.eval(()=>window.__voxelHeroes.game.keys.keyCount('tower-tide'))===1,'tide floor keeps its own key');await t.walkTo(8,3);await t.stick(0,-1,.85);await go('north','The Tide Memory Gate');
 for(const x of[3.5,12.5]){await t.walkTo(x,5);await item('fire-wand','north');}await t.shot('11-tide-bowls');await go('west','The Memory Crown');await chest(8,4);await go('east','The Tide Memory Gate');await t.walkTo(7.5,2);await t.stick(0,-1,.85);await warp(7,0,'tower-tide-boss:0,0');await t.step(4);await safe();
 t.expect(await t.eval(()=>window.__voxelHeroes.entities.some(e=>e.type==='boss-beast'&&e.refight&&e.segments.length===4)),'third floor uses Nacre rematch with four linked tentacles');await t.shot('12-tide-rematch');
 await t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-beast');b.surface();h.game.damage.dealDamage(b,{amount:999,source:'sword',from:h.player});});await t.step(.3);await warp(10,0,'tower-tide:1,0');await chest(8,4);await warp(7,0,'tower-crown:1,2');
 const saved=await t.save();await t.load(saved);await settle();t.expect(await t.eval(()=>{const h=window.__voxelHeroes;return ['tower-hive','tower-watch','tower-tide'].every(id=>h.game.dungeons.bossDefeated(id))&&h.state.gear.shield===6&&h.game.inventory.hasItem('spell-truesight')&&h.state.swords.owned.includes('blade-dawn');}),'save/load keeps rematches cleared, learned sight and earned gear');
 await go('north','The Crown Guard');await kill();await chest(8,4);await go('north','The Last Door');await t.shot('13-last-door');await t.walkTo(8,2);await t.stick(0,-1,.85);await warp(7,0,'tower-final:0,0');await t.step(4);await safe();await clearShots();
 await t.eval(()=>{const b=window.__voxelHeroes.entities.find(e=>e.type==='boss-bishop');b.ai.phase='hold';b.ai.t=4;});
 t.expect(await t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-bishop');return h.game.damage.dealDamage(b,{amount:10,source:'sword',from:h.player}).result==='blocked'&&b.hp===75;}),'final keeper blocks a strike without Truesight');
 const sightMagic=await t.eval(()=>{const h=window.__voxelHeroes;return{before:h.state.magic,cost:h.game.spells.spellCost('spell-truesight')};});
 await item('spell-truesight','north',.2);t.expect(await t.eval(()=>window.__voxelHeroes.state.magic)===sightMagic.before-sightMagic.cost,'real Truesight input spends the class-adjusted spell cost');
 await t.step(15.1);t.expect(await t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-bishop');return !h.game.effects.effectActive('truesight')&&!b.shadow.visible&&!b.mesh.castShadow&&b.segments.every(e=>!e.shadow.visible);}), 'the personal shadow cue disappears when Truesight expires');
 await clearShots();await t.eval(()=>{const b=window.__voxelHeroes.entities.find(e=>e.type==='boss-bishop');b.ai.phase='hold';b.ai.t=4;});await item('spell-truesight','north',.2);
 const sight=await t.eval(()=>{const b=window.__voxelHeroes.entities.find(e=>e.type==='boss-bishop');return{visible:b.shadow.visible,copies:b.segments.filter(e=>e.shadow.visible).length};});t.expect(sight.visible&&sight.copies===0,'real Truesight reveals only the real body shadow');await t.shot('14-truesight-reflections');
 t.expect(await t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-bishop');return h.game.damage.dealDamage(b.segments[0],{amount:10,source:'sword',from:h.player}).result==='blocked'&&b.hp===75;}),'sight does not turn a false copy into a damage target');
 for(let i=0;i<15;i++){
  const live=await t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-bishop');if(!b)return false;for(const e of [...h.entities])if(e.kind==='projectile'||e.type==='crown-wisp')e.remove();b.ai.phase='hold';b.ai.t=4;h.game.effects.startEffect('truesight',2);h.game.hero.hero.place(b.x-h.screen().x0,b.z-h.screen().z0+1.3,Math.PI);return true;});
  if(!live)break;await t.tap('sword');await t.step(.55);
  if(i===3||i===7){const bodies=await t.eval(()=>{const b=window.__voxelHeroes.entities.find(e=>e.type==='boss-bishop');return b?b.segments.length+1:0;});if(i===3)t.expect(bodies>=4,'four bodies appear as the keeper weakens');if(i===7&&bodies)t.expect(bodies===5,'five bodies appear at low life');}
 }
 await t.step(4);await safe();await clearShots();t.expect(await t.eval(()=>window.__voxelHeroes.state.flags.has('tower:mask-broken')&&window.__voxelHeroes.entities.filter(e=>e.type==='boss-king').length===1),'real sword inputs break the mask and start one final king');await t.shot('15-hollow-crown');
 // The charged attack is unguardable; ordinary storm shots and the marked lightning use tier six.
 await t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-king');b.ai.phase='recover';b.ai.t=20;h.game.hero.hero.place(11,12,Math.PI);h.player.invT=0;h.input.down('guard');h.spawn('crown-storm',11,10,{dir:{x:0,z:1},speed:5});});const hp=await t.eval(()=>window.__voxelHeroes.state.hp);await t.step(.6);t.expect(await t.eval(()=>window.__voxelHeroes.state.hp)===hp,'earned Bastion Shield blocks a real storm projectile');
 await t.eval(()=>{const h=window.__voxelHeroes;h.state.gear.shield=5;h.player.invT=0;h.spawn('crown-storm',11,10,{dir:{x:0,z:1},speed:5});});await t.step(.6);t.expect(await t.eval(()=>window.__voxelHeroes.state.hp)<hp,'tier five cannot block the tier-six storm');
 await t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-king');h.input.up('guard');h.state.gear.shield=6;h.setHp(h.state.maxHp);h.player.invT=0;b.ai.phase='stalk';b.ai.t=0;b.ai.attack=1;});await t.step(.2);t.expect(await t.eval(()=>window.__voxelHeroes.entities.filter(e=>e.type==='crown-lightning').length)===5,'actual king AI marks the hero and four corners for lightning');await t.step(.4);t.expect(await t.eval(()=>window.__voxelHeroes.state.hp)===hp,'a lightning floor mark is harmless during its readable warning');await t.shot('16-lightning-tell');await t.stick(1,0,.45);await t.step(.6);t.expect(await t.eval(()=>window.__voxelHeroes.state.hp)===hp,'real movement leaves the lightning strike without damage');
 await t.eval(()=>{const h=window.__voxelHeroes;h.game.hero.hero.place(11,12,Math.PI);h.player.invT=0;h.input.down('guard');h.spawn('crown-charge',11,10,{dir:{x:0,z:1},speed:6});});await t.step(.6);t.expect(await t.eval(()=>window.__voxelHeroes.state.hp)<hp,'bright charged shot pierces even the earned Bastion Shield');await t.eval(()=>window.__voxelHeroes.input.up('guard'));await safe();await clearShots();
 await t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-king');b.hp=42;b.ai.phase='stalk';b.ai.t=0;b.ai.attack=2;h.game.hero.hero.place(11,12,Math.PI);});await t.step(.2);t.expect(await t.eval(()=>window.__voxelHeroes.entities.find(e=>e.type==='boss-king').ai.phase)==='charge-tell','actual low-life AI winds up its charged shot');await t.shot('17-charge-line');await t.step(1.3);t.expect(await t.eval(()=>window.__voxelHeroes.entities.some(e=>e.type==='crown-charge')),'actual wind-up emits the unguardable shot');
 // Restore the full body to verify the complete sword damage total, rather than counting the low-life fixture as combat.
 await t.eval(()=>{const h=window.__voxelHeroes;h.entities.find(e=>e.type==='boss-king').hp=140;});
 for(let i=0;i<25;i++){const live=await t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-king');if(!b)return false;for(const e of [...h.entities])if(e.kind==='projectile')e.remove();b.ai.phase='recover';b.ai.t=9;b.ai.shots=0;h.game.hero.hero.place(b.x-h.screen().x0,b.z-h.screen().z0+2.2,Math.PI);return true;});if(!live)break;await t.tap('sword');await t.step(.55);}
 await t.step(1.2);t.expect(await t.eval(()=>window.__voxelHeroes.state.flags.has('campaign:complete')&&window.__voxelHeroes.state.mode==='ending'),'actual sword inputs remove 140 HP and enter the campaign ending');await t.step(1);await t.shot('18-ending');await t.page.setViewportSize({width:390,height:844});await t.shot('19-ending-phone');t.expect(await t.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'ending fits phone width');await t.page.setViewportSize({width:1280,height:720});
 for(let i=0;i<3;i++){await t.tap('confirm');await t.step(.4);}await settle();t.expect((await t.state()).area==='v1','ending returns to the town hub');await t.shot('20-homecoming');
 const completed=await t.save();await t.load(completed);await settle();t.expect(await t.eval(()=>window.__voxelHeroes.state.flags.has('campaign:complete')),'saved victory remains complete');
 await t.teleport('ow-4-3:1,1',7,5);await t.eval(()=>{const h=window.__voxelHeroes,n=h.entities.find(e=>e.type==='npc-king');n.onInteract(h.player);});await answer();t.expect(await t.eval(()=>window.__voxelHeroes.state.flags.has('overworld:celebrated')),'real King Aldric homecoming acknowledges the completed campaign');
 await t.teleport('tower-tide-boss:0,0',11,13);await t.step(1);t.expect(await t.eval(()=>!window.__voxelHeroes.entities.some(e=>e.type==='boss-beast')),'cleared rematch does not respawn after save/load and revisit');
}
