import { useClockTool } from '../lib/tower-clock.mjs';
export const description = 'Active Fourfold Clock: no timer exit, real anchor tool collisions, powder supply, wrong-tool rejection, projectile pressure/cover/shield, interruption, fewer copies, real grapple pull, partial/full saves, any-order solve and earned-save compatibility. Earlier campaign, initial gear, invulnerability and isolated attack/position fixtures are disclosed. All audio is muted and NPC recordings disabled.';
export default async function(t) {
 const flag=id=>t.eval(id=>window.__voxelHeroes.game.state.hasFlag(id),id);
 const clock=()=>t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-bishop'&&!e.removed);return {anchors:['return','break','draw','kindle'].filter(id=>h.game.state.hasFlag('tower:clock:'+id)),keeper:b?{hp:b.hp,phase:b.ai.phase,clock:b.ai.clock,copies:b.segments.length}:null,notes:h.entities.filter(e=>e.type==='crown-shot'&&!e.removed).map(e=>({tier:e.tier,owner:e.owner})),mode:h.state.mode};});
 const photo=async name=>{await t.page.waitForFunction(()=>!window.__voxelHeroes.game.banner.bannerView().visible);await t.eval(()=>window.__voxelHeroes.player.hero.root.visible=true);await t.shot(name);};
 const setup=async()=>{
  await t.eval(()=>{const h=window.__voxelHeroes;h.game.progress.startNewGame({prologue:false});h.state.settings.muted=true;h.game.audio.setMuted(true);h.game.audio.setVolumes({master:0});h.game.settings.setSetting('npcVoices',false);for(let n=1;n<=4;n++){h.game.state.setFlag('orb:'+n);h.game.state.setFlag('boss:d'+n);h.game.state.setFlag('dungeon:d'+n+':complete');h.game.state.setFlag('dungeon:d'+n+':entered');h.game.dungeons.giveBossKey('d'+n);}h.game.state.setFlag('overworld:talked:king');for(const id of['boomerang','bombs','grapple','fire-wand'])h.game.inventory.giveItem(id);h.give('blade-start');h.game.swords.equipSword('blade-start');h.player.invT=999;});
  await t.teleport('tower-trial:0,0',11,13.5);await t.step(4);
 };
 await setup();
 t.expect((await clock()).keeper?.copies===2&&(await clock()).anchors.length===0,'the first meeting has three native bodies and four unturned windings');
 const initialGoal=await t.eval(()=>window.__voxelHeroes.game.objective.objectiveText());t.expect(/Clock.*0\/4.*Return/i.test(initialGoal),'main campaign guidance names the first physical anchor and its tool: '+initialGoal);
 await photo('01-four-borrowed-hours');
 await t.step(121);
 t.expect(!await flag('tower:trial')&&(await clock()).keeper.clock>120,'121 simulated seconds cannot substitute for unwinding the clock');
 await t.walkTo(10.5,2.1);await t.stick(0,-1,.8);await t.step(.3);t.expect((await t.state()).key==='tower-trial:0,0','actual northward movement cannot cross the gated stair before the tools are used');
 const wrong=await t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-bishop');return h.game.damage.dealDamage(b,{amount:999,source:'sword',from:h.player,truesight:true});});
 t.expect(wrong.result==='blocked'&&(await clock()).keeper.hp===75,'even sight and a damage fixture cannot defeat the protected trial body');
 await useClockTool(t,'fire-wand',4.5,9.5);
 t.expect((await clock()).anchors.length===0,'a real flame cannot turn the returning-blade anchor');
 await t.eval(()=>{const h=window.__voxelHeroes,s=h.screen();h.game.hero.hero.place(11,13.5);h.state.inventory.ammo.bombs=0;h.game.hero.hero.setFacing('north');h.player.lockT=h.player.knockT=h.player.stallT=0;});await t.tap('sword');
 t.expect(await t.eval(()=>window.__voxelHeroes.game.inventory.ammo('bombs'))>0,'actual supply interaction refills an empty bomb pouch');
 await t.eval(()=>{const h=window.__voxelHeroes,b=h.entities.find(e=>e.type==='boss-bishop');for(const e of [...h.entities])if(e.kind==='projectile')e.remove();h.game.hero.hero.place(11,11);b.ai.phase='appear';b.ai.t=0;});await t.step(.02);
 t.expect((await clock()).notes.length===3&&(await clock()).notes.every(n=>n.tier===2),'the natural trial volley is three ordinary tier-two shots');
 const pressure=async(cover,shield)=>t.eval(([cover,shield])=>{const h=window.__voxelHeroes,s=h.screen(),b=h.entities.find(e=>e.type==='boss-bishop');for(const e of [...h.entities])if(e.kind==='projectile'||e.type==='crown-wisp')e.remove();const x=cover?4.5:11;h.game.hero.hero.place(x,9.5);h.game.hero.hero.setFacing('north');h.player.invT=h.player.lockT=h.player.knockT=h.player.stallT=h.player.attackT=0;h.state.gear.shield=shield;h.setHp(h.state.maxHp);for(const e of[b,...b.segments]){e.x=s.x0+x;e.z=s.z0+5;e.present();}b.ai.phase='appear';b.ai.t=0;b.ai.addT=999;window.__clockHits=[];if(!window.__clockHitListener){window.__clockHitListener=true;h.game.events.on('hero-hit',e=>{if(e.source?.type==='crown-shot')window.__clockHits.push(e.result);});}},[cover,shield]);
 await pressure(true,0);const coverHp=(await t.state()).hp;await t.step(1.25);
 t.expect((await t.state()).hp===coverHp&&(await clock()).notes.length===0&&(await clock()).anchors.length===0,'three native enemy shots stop at the western pedestal without hurting the unguarded hero or turning it');
 await pressure(false,2);const guardHp=(await t.state()).hp;await t.eval(()=>window.__voxelHeroes.input.down('guard'));await t.step(1.25);await t.eval(()=>window.__voxelHeroes.input.up('guard'));
 t.expect((await t.state()).hp===guardHp&&await t.eval(()=>window.__clockHits.length>0&&window.__clockHits.every(r=>r==='blocked')),'real held tier-two guard blocks the unprotected trial volley');
 await pressure(false,1);await t.eval(()=>window.__voxelHeroes.input.down('guard'));await t.step(1.25);await t.eval(()=>{const h=window.__voxelHeroes;h.input.up('guard');h.player.invT=999;});
 t.expect((await t.state()).hp<guardHp&&await t.eval(()=>window.__clockHits.includes('hit')),'a weaker held shield takes real projectile damage rather than bypassing the encounter');

 await useClockTool(t,'boomerang',4.5,9.5);
 t.expect(await flag('tower:clock:return')&&(await clock()).anchors.length===1,'an actual returning throw turns only the western anchor');
 t.expect((await clock()).notes.length===0,'freeing one winding scatters the pending enemy volley');
 await photo('02-the-hour-of-return');
 await useClockTool(t,'boomerang',4.5,9.5);
 t.expect((await clock()).anchors.length===1,'repeated returning throws do not advance another winding');
 await useClockTool(t,'bombs',17.5,9.15,'north',.1);await t.stick(0,1,.5);await t.step(2.6);
 t.expect(await flag('tower:clock:break')&&(await clock()).anchors.length===2,'the native placed-bomb blast turns the eastern brass anchor');
 t.expect((await clock()).keeper.copies===1,'two released hours remove one attacking copy');
 await photo('03-brass-can-change');
 await t.eval(()=>{const h=window.__voxelHeroes;h.game.hero.hero.place(10.5,13.5);h.game.hero.hero.setFacing('south');h.player.lockT=h.player.knockT=h.player.stallT=0;});await t.stick(0,1,.7);await t.step(1.6);
 t.expect((await t.state()).key==='tidecoast:2,2'&&(await clock()).anchors.length===2&&!await flag('tower:trial'),'actual southern retreat preserves the two unfinished clock windings');
 await t.walkTo(8.5,4.5);await t.eval(()=>{const h=window.__voxelHeroes;h.game.inventory.selectItem('fire-wand');h.game.hero.hero.setFacing('north');});await t.tap('item');await t.step(.6);await t.walkTo(8.5,2.5,{allowHooks:true,soft:true});await t.step(4);
 t.expect((await t.state()).key==='tower-trial:0,0'&&(await clock()).keeper?.copies===1&&(await clock()).anchors.length===2,'actual doorway return resumes the reduced clock encounter');

 const saved=await t.save();await t.load(saved);await t.eval(()=>window.__voxelHeroes.player.invT=999);await t.step(4);
 t.expect((await clock()).anchors.length===2&&(await clock()).keeper.copies===1&&!await flag('tower:trial'),'partial save restores both windings and the reduced encounter without clearing the trial');
 t.expect(await t.eval(()=>window.__voxelHeroes.game.objective.objectiveText()).then(v=>/2\/4.*Draw/i.test(v)),'restored campaign guidance names the next unsolved tool');
 await useClockTool(t,'grapple',7.5,13.5,'north',1);
 t.expect(await flag('tower:clock:draw')&&(await clock()).anchors.length===3,'a real zero-damage hook turns the southwestern anchor');
 t.expect(await t.eval(()=>{const h=window.__voxelHeroes,s=h.screen();return Math.abs(h.player.x-s.x0-7.5)<.3&&h.player.z-s.z0<13;}),'the same accepted hook physically pulls the hero toward its winding');
 await photo('04-the-hour-of-reaching');
 await useClockTool(t,'fire-wand',14.5,13.5);await t.step(.2);
 t.expect((await clock()).anchors.length===4&&await flag('tower:trial'),'the real fourth-tool hit frees the city clock');
 t.expect(!(await clock()).keeper&&await t.eval(()=>!window.__voxelHeroes.entities.some(e=>['bishop-copy','crown-wisp','crown-shot'].includes(e.type))),'completion removes the reflections, copies, wisps and hostile shots');
 t.expect(await flag('boss:tower-trial')&&await t.eval(()=>!window.__voxelHeroes.entities.some(e=>e.type==='heart-container')),'the ordinary shared trial boss flag opens the stair without a bonus boss heart');
 await photo('05-the-clock-moves');
 const completed=await t.save();await t.load(completed);await t.step(1);
 t.expect(await flag('tower:trial')&&(await clock()).anchors.length===4&&!(await clock()).keeper,'full save preserves the earned clock and prevents a new trial');
 await t.walkTo(10.5,.5,{allowHooks:true,soft:true});await t.step(1.6);
 t.expect((await t.state()).key==='tower-hive:1,2','the hero physically climbs the now-open northern stair');
 await setup();
 await useClockTool(t,'fire-wand',14.5,13.5);await useClockTool(t,'grapple',7.5,13.5,'north',1);
 t.expect((await clock()).anchors.join(',')==='draw,kindle'&&!await flag('tower:trial'),'a different real tool order preserves exactly those two completed windings');
 await t.eval(()=>{const h=window.__voxelHeroes;h.game.state.setFlag('tower:trial');h.game.state.setFlag('boss:tower-trial');for(const id of['return','break','draw','kindle'])h.game.state.clearFlag('tower:clock:'+id);});const legacy=await t.save();await t.load(legacy);await t.step(1);
 t.expect(await flag('tower:trial')&&!(await clock()).keeper,'an earned pre-anchor save remains complete without solving new windings');
 await photo('06-an-earned-memory');
}
